// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module simd_MAC (
        ap_clk,
        ap_rst,
        wpack_0_V_read,
        wpack_1_V_read,
        wpack_2_V_read,
        wpack_3_V_read,
        wpack_4_V_read,
        wpack_5_V_read,
        wpack_6_V_read,
        wpack_7_V_read,
        ipack_0_V_read,
        ipack_1_V_read,
        ipack_2_V_read,
        ipack_3_V_read,
        ipack_4_V_read,
        ipack_5_V_read,
        ipack_6_V_read,
        ipack_7_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [25:0] wpack_0_V_read;
input  [25:0] wpack_1_V_read;
input  [25:0] wpack_2_V_read;
input  [25:0] wpack_3_V_read;
input  [25:0] wpack_4_V_read;
input  [25:0] wpack_5_V_read;
input  [25:0] wpack_6_V_read;
input  [25:0] wpack_7_V_read;
input  [14:0] ipack_0_V_read;
input  [14:0] ipack_1_V_read;
input  [14:0] ipack_2_V_read;
input  [14:0] ipack_3_V_read;
input  [14:0] ipack_4_V_read;
input  [14:0] ipack_5_V_read;
input  [14:0] ipack_6_V_read;
input  [14:0] ipack_7_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;

wire  signed [40:0] mul_ln1352_fu_729_p2;
reg  signed [40:0] mul_ln1352_reg_793;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire  signed [40:0] mul_ln1352_12_fu_737_p2;
reg  signed [40:0] mul_ln1352_12_reg_799;
wire   [10:0] trunc_ln700_fu_174_p1;
reg   [10:0] trunc_ln700_reg_805;
wire   [10:0] trunc_ln700_62_fu_177_p1;
reg   [10:0] trunc_ln700_62_reg_810;
wire   [21:0] trunc_ln700_63_fu_180_p1;
reg   [21:0] trunc_ln700_63_reg_815;
wire   [21:0] trunc_ln700_64_fu_183_p1;
reg   [21:0] trunc_ln700_64_reg_820;
wire  signed [40:0] mul_ln1352_13_fu_745_p2;
reg  signed [40:0] mul_ln1352_13_reg_825;
wire   [21:0] trunc_ln700_65_fu_194_p1;
reg   [21:0] trunc_ln700_65_reg_831;
wire   [10:0] trunc_ln700_66_fu_197_p1;
reg   [10:0] trunc_ln700_66_reg_836;
wire  signed [40:0] mul_ln1352_14_fu_753_p2;
reg  signed [40:0] mul_ln1352_14_reg_841;
wire   [10:0] trunc_ln700_67_fu_208_p1;
reg   [10:0] trunc_ln700_67_reg_847;
wire   [21:0] trunc_ln700_68_fu_211_p1;
reg   [21:0] trunc_ln700_68_reg_852;
wire  signed [40:0] mul_ln1352_15_fu_761_p2;
reg  signed [40:0] mul_ln1352_15_reg_857;
wire  signed [40:0] mul_ln1352_16_fu_769_p2;
reg  signed [40:0] mul_ln1352_16_reg_863;
wire   [10:0] trunc_ln700_71_fu_230_p1;
reg   [10:0] trunc_ln700_71_reg_869;
wire   [10:0] trunc_ln700_72_fu_233_p1;
reg   [10:0] trunc_ln700_72_reg_874;
wire   [21:0] trunc_ln700_73_fu_236_p1;
reg   [21:0] trunc_ln700_73_reg_879;
wire   [21:0] trunc_ln700_74_fu_239_p1;
reg   [21:0] trunc_ln700_74_reg_884;
wire  signed [40:0] mul_ln1352_17_fu_777_p2;
reg  signed [40:0] mul_ln1352_17_reg_889;
wire   [21:0] trunc_ln700_75_fu_250_p1;
reg   [21:0] trunc_ln700_75_reg_895;
wire   [10:0] trunc_ln700_76_fu_253_p1;
reg   [10:0] trunc_ln700_76_reg_900;
wire  signed [40:0] mul_ln1352_18_fu_785_p2;
reg  signed [40:0] mul_ln1352_18_reg_905;
wire   [10:0] trunc_ln700_77_fu_264_p1;
reg   [10:0] trunc_ln700_77_reg_911;
wire   [21:0] trunc_ln700_78_fu_267_p1;
reg   [21:0] trunc_ln700_78_reg_916;
wire   [10:0] add_ln78_fu_390_p2;
reg   [10:0] add_ln78_reg_921;
wire   [10:0] add_ln78_1_fu_418_p2;
reg   [10:0] add_ln78_1_reg_926;
reg   [9:0] tmp_reg_931;
reg   [0:0] tmp_31_reg_936;
wire   [10:0] add_ln78_3_fu_566_p2;
reg   [10:0] add_ln78_3_reg_941;
wire   [10:0] add_ln78_4_fu_594_p2;
reg   [10:0] add_ln78_4_reg_946;
reg   [9:0] tmp_9_reg_951;
reg   [0:0] tmp_34_reg_956;
wire   [11:0] add_ln700_15_fu_622_p2;
reg   [11:0] add_ln700_15_reg_961;
wire    ap_block_pp0_stage0;
wire  signed [41:0] sext_ln215_13_fu_270_p1;
wire  signed [41:0] sext_ln700_fu_273_p1;
wire  signed [41:0] add_ln700_fu_280_p2;
wire  signed [41:0] sext_ln700_11_fu_290_p1;
wire  signed [41:0] sext_ln700_12_fu_301_p1;
wire  signed [41:0] add_ln700_19_fu_308_p2;
(* use_dsp48 = "no" *) wire   [40:0] add_ln700_76_fu_276_p2;
(* use_dsp48 = "no" *) wire   [40:0] add_ln700_77_fu_304_p2;
wire  signed [42:0] sext_ln700_13_fu_314_p1;
wire  signed [42:0] sext_ln700_10_fu_286_p1;
wire   [32:0] trunc_ln700_69_fu_324_p1;
wire   [32:0] trunc_ln700_70_fu_328_p1;
wire   [21:0] add_ln700_13_fu_293_p2;
wire   [21:0] add_ln700_24_fu_344_p2;
wire   [10:0] add_ln215_fu_297_p2;
wire   [10:0] add_ln700_26_fu_354_p2;
wire   [41:0] add_ln700_20_fu_318_p2;
wire   [10:0] add_ln700_27_fu_359_p2;
wire   [0:0] tmp_29_fu_378_p3;
wire   [10:0] p_Result_s_fu_368_p4;
wire   [10:0] zext_ln78_fu_386_p1;
wire   [21:0] add_ln700_25_fu_349_p2;
wire   [0:0] tmp_30_fu_406_p3;
wire   [10:0] p_Result_4_fu_396_p4;
wire   [10:0] zext_ln78_1_fu_414_p1;
wire   [42:0] add_ln700_11_fu_332_p2;
wire   [32:0] add_ln700_23_fu_338_p2;
wire   [10:0] trunc_ln647_fu_364_p1;
wire  signed [41:0] sext_ln215_19_fu_446_p1;
wire  signed [41:0] sext_ln700_17_fu_449_p1;
wire  signed [41:0] add_ln700_12_fu_456_p2;
wire  signed [41:0] sext_ln700_19_fu_466_p1;
wire  signed [41:0] sext_ln700_20_fu_477_p1;
wire  signed [41:0] add_ln700_29_fu_484_p2;
(* use_dsp48 = "no" *) wire   [40:0] add_ln700_78_fu_452_p2;
(* use_dsp48 = "no" *) wire   [40:0] add_ln700_79_fu_480_p2;
wire  signed [42:0] sext_ln700_21_fu_490_p1;
wire  signed [42:0] sext_ln700_18_fu_462_p1;
wire   [32:0] trunc_ln700_79_fu_500_p1;
wire   [32:0] trunc_ln700_80_fu_504_p1;
wire   [21:0] add_ln700_28_fu_469_p2;
wire   [21:0] add_ln700_34_fu_520_p2;
wire   [10:0] add_ln215_1_fu_473_p2;
wire   [10:0] add_ln700_36_fu_530_p2;
wire   [41:0] add_ln700_30_fu_494_p2;
wire   [10:0] add_ln700_37_fu_535_p2;
wire   [0:0] tmp_32_fu_554_p3;
wire   [10:0] p_Result_62_1_fu_544_p4;
wire   [10:0] zext_ln78_3_fu_562_p1;
wire   [21:0] add_ln700_35_fu_525_p2;
wire   [0:0] tmp_33_fu_582_p3;
wire   [10:0] p_Result_63_1_fu_572_p4;
wire   [10:0] zext_ln78_4_fu_590_p1;
wire   [42:0] add_ln700_14_fu_508_p2;
wire   [32:0] add_ln700_33_fu_514_p2;
wire   [10:0] trunc_ln647_8_fu_540_p1;
wire  signed [11:0] sext_ln700_22_fu_618_p1;
wire  signed [11:0] sext_ln700_14_fu_442_p1;
wire  signed [10:0] sext_ln647_fu_628_p1;
wire   [10:0] zext_ln78_2_fu_631_p1;
wire   [10:0] add_ln78_2_fu_634_p2;
wire  signed [10:0] sext_ln647_1_fu_650_p1;
wire   [10:0] zext_ln78_5_fu_653_p1;
wire  signed [11:0] sext_ln700_24_fu_665_p1;
wire  signed [11:0] sext_ln700_15_fu_640_p1;
wire   [11:0] add_ln700_16_fu_668_p2;
wire  signed [11:0] sext_ln700_26_fu_678_p1;
wire  signed [11:0] sext_ln700_16_fu_643_p1;
wire   [11:0] add_ln700_17_fu_681_p2;
wire   [10:0] add_ln78_5_fu_656_p2;
wire  signed [11:0] sext_ln700_28_fu_691_p1;
wire  signed [11:0] sext_ln215_17_fu_646_p1;
wire   [11:0] add_ln700_18_fu_695_p2;
wire  signed [15:0] sext_ln700_23_fu_662_p1;
wire  signed [15:0] sext_ln700_25_fu_674_p1;
wire  signed [15:0] sext_ln700_27_fu_687_p1;
wire  signed [15:0] sext_ln700_29_fu_701_p1;
wire   [14:0] mul_ln1352_fu_729_p1;
wire   [14:0] mul_ln1352_12_fu_737_p1;
wire   [14:0] mul_ln1352_13_fu_745_p1;
wire   [14:0] mul_ln1352_14_fu_753_p1;
wire   [14:0] mul_ln1352_15_fu_761_p1;
wire   [14:0] mul_ln1352_16_fu_769_p1;
wire   [14:0] mul_ln1352_17_fu_777_p1;
wire   [14:0] mul_ln1352_18_fu_785_p1;
reg    ap_ce_reg;
reg  signed [25:0] wpack_0_V_read_int_reg;
reg  signed [25:0] wpack_1_V_read_int_reg;
reg  signed [25:0] wpack_2_V_read_int_reg;
reg  signed [25:0] wpack_3_V_read_int_reg;
reg  signed [25:0] wpack_4_V_read_int_reg;
reg  signed [25:0] wpack_5_V_read_int_reg;
reg  signed [25:0] wpack_6_V_read_int_reg;
reg  signed [25:0] wpack_7_V_read_int_reg;
reg   [14:0] ipack_0_V_read_int_reg;
reg   [14:0] ipack_1_V_read_int_reg;
reg   [14:0] ipack_2_V_read_int_reg;
reg   [14:0] ipack_3_V_read_int_reg;
reg   [14:0] ipack_4_V_read_int_reg;
reg   [14:0] ipack_5_V_read_int_reg;
reg   [14:0] ipack_6_V_read_int_reg;
reg   [14:0] ipack_7_V_read_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
wire   [40:0] mul_ln1352_12_fu_737_p10;
wire   [40:0] mul_ln1352_13_fu_745_p10;
wire   [40:0] mul_ln1352_14_fu_753_p10;
wire   [40:0] mul_ln1352_15_fu_761_p10;
wire   [40:0] mul_ln1352_16_fu_769_p10;
wire   [40:0] mul_ln1352_17_fu_777_p10;
wire   [40:0] mul_ln1352_18_fu_785_p10;
wire   [40:0] mul_ln1352_fu_729_p10;

ultra_net_mul_mulbml #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 41 ))
ultra_net_mul_mulbml_U357(
    .din0(wpack_0_V_read_int_reg),
    .din1(mul_ln1352_fu_729_p1),
    .dout(mul_ln1352_fu_729_p2)
);

ultra_net_mul_mulbml #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 41 ))
ultra_net_mul_mulbml_U358(
    .din0(wpack_1_V_read_int_reg),
    .din1(mul_ln1352_12_fu_737_p1),
    .dout(mul_ln1352_12_fu_737_p2)
);

ultra_net_mul_mulbml #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 41 ))
ultra_net_mul_mulbml_U359(
    .din0(wpack_2_V_read_int_reg),
    .din1(mul_ln1352_13_fu_745_p1),
    .dout(mul_ln1352_13_fu_745_p2)
);

ultra_net_mul_mulbml #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 41 ))
ultra_net_mul_mulbml_U360(
    .din0(wpack_3_V_read_int_reg),
    .din1(mul_ln1352_14_fu_753_p1),
    .dout(mul_ln1352_14_fu_753_p2)
);

ultra_net_mul_mulbml #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 41 ))
ultra_net_mul_mulbml_U361(
    .din0(wpack_4_V_read_int_reg),
    .din1(mul_ln1352_15_fu_761_p1),
    .dout(mul_ln1352_15_fu_761_p2)
);

ultra_net_mul_mulbml #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 41 ))
ultra_net_mul_mulbml_U362(
    .din0(wpack_5_V_read_int_reg),
    .din1(mul_ln1352_16_fu_769_p1),
    .dout(mul_ln1352_16_fu_769_p2)
);

ultra_net_mul_mulbml #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 41 ))
ultra_net_mul_mulbml_U363(
    .din0(wpack_6_V_read_int_reg),
    .din1(mul_ln1352_17_fu_777_p1),
    .dout(mul_ln1352_17_fu_777_p2)
);

ultra_net_mul_mulbml #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 41 ))
ultra_net_mul_mulbml_U364(
    .din0(wpack_7_V_read_int_reg),
    .din1(mul_ln1352_18_fu_785_p1),
    .dout(mul_ln1352_18_fu_785_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln700_15_reg_961 <= add_ln700_15_fu_622_p2;
        add_ln78_1_reg_926 <= add_ln78_1_fu_418_p2;
        add_ln78_3_reg_941 <= add_ln78_3_fu_566_p2;
        add_ln78_4_reg_946 <= add_ln78_4_fu_594_p2;
        add_ln78_reg_921 <= add_ln78_fu_390_p2;
        mul_ln1352_12_reg_799 <= mul_ln1352_12_fu_737_p2;
        mul_ln1352_13_reg_825 <= mul_ln1352_13_fu_745_p2;
        mul_ln1352_14_reg_841 <= mul_ln1352_14_fu_753_p2;
        mul_ln1352_15_reg_857 <= mul_ln1352_15_fu_761_p2;
        mul_ln1352_16_reg_863 <= mul_ln1352_16_fu_769_p2;
        mul_ln1352_17_reg_889 <= mul_ln1352_17_fu_777_p2;
        mul_ln1352_18_reg_905 <= mul_ln1352_18_fu_785_p2;
        mul_ln1352_reg_793 <= mul_ln1352_fu_729_p2;
        tmp_31_reg_936 <= add_ln700_23_fu_338_p2[32'd32];
        tmp_34_reg_956 <= add_ln700_33_fu_514_p2[32'd32];
        tmp_9_reg_951 <= {{add_ln700_14_fu_508_p2[42:33]}};
        tmp_reg_931 <= {{add_ln700_11_fu_332_p2[42:33]}};
        trunc_ln700_62_reg_810 <= trunc_ln700_62_fu_177_p1;
        trunc_ln700_63_reg_815 <= trunc_ln700_63_fu_180_p1;
        trunc_ln700_64_reg_820 <= trunc_ln700_64_fu_183_p1;
        trunc_ln700_65_reg_831 <= trunc_ln700_65_fu_194_p1;
        trunc_ln700_66_reg_836 <= trunc_ln700_66_fu_197_p1;
        trunc_ln700_67_reg_847 <= trunc_ln700_67_fu_208_p1;
        trunc_ln700_68_reg_852 <= trunc_ln700_68_fu_211_p1;
        trunc_ln700_71_reg_869 <= trunc_ln700_71_fu_230_p1;
        trunc_ln700_72_reg_874 <= trunc_ln700_72_fu_233_p1;
        trunc_ln700_73_reg_879 <= trunc_ln700_73_fu_236_p1;
        trunc_ln700_74_reg_884 <= trunc_ln700_74_fu_239_p1;
        trunc_ln700_75_reg_895 <= trunc_ln700_75_fu_250_p1;
        trunc_ln700_76_reg_900 <= trunc_ln700_76_fu_253_p1;
        trunc_ln700_77_reg_911 <= trunc_ln700_77_fu_264_p1;
        trunc_ln700_78_reg_916 <= trunc_ln700_78_fu_267_p1;
        trunc_ln700_reg_805 <= trunc_ln700_fu_174_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= sext_ln700_23_fu_662_p1;
        ap_return_1_int_reg <= sext_ln700_25_fu_674_p1;
        ap_return_2_int_reg <= sext_ln700_27_fu_687_p1;
        ap_return_3_int_reg <= sext_ln700_29_fu_701_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        ipack_0_V_read_int_reg <= ipack_0_V_read;
        ipack_1_V_read_int_reg <= ipack_1_V_read;
        ipack_2_V_read_int_reg <= ipack_2_V_read;
        ipack_3_V_read_int_reg <= ipack_3_V_read;
        ipack_4_V_read_int_reg <= ipack_4_V_read;
        ipack_5_V_read_int_reg <= ipack_5_V_read;
        ipack_6_V_read_int_reg <= ipack_6_V_read;
        ipack_7_V_read_int_reg <= ipack_7_V_read;
        wpack_0_V_read_int_reg <= wpack_0_V_read;
        wpack_1_V_read_int_reg <= wpack_1_V_read;
        wpack_2_V_read_int_reg <= wpack_2_V_read;
        wpack_3_V_read_int_reg <= wpack_3_V_read;
        wpack_4_V_read_int_reg <= wpack_4_V_read;
        wpack_5_V_read_int_reg <= wpack_5_V_read;
        wpack_6_V_read_int_reg <= wpack_6_V_read;
        wpack_7_V_read_int_reg <= wpack_7_V_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = sext_ln700_23_fu_662_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = sext_ln700_25_fu_674_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = sext_ln700_27_fu_687_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = sext_ln700_29_fu_701_p1;
    end
end

assign add_ln215_1_fu_473_p2 = (trunc_ln700_71_reg_869 + trunc_ln700_72_reg_874);

assign add_ln215_fu_297_p2 = (trunc_ln700_reg_805 + trunc_ln700_62_reg_810);

assign add_ln700_11_fu_332_p2 = ($signed(sext_ln700_13_fu_314_p1) + $signed(sext_ln700_10_fu_286_p1));

assign add_ln700_12_fu_456_p2 = ($signed(sext_ln215_19_fu_446_p1) + $signed(sext_ln700_17_fu_449_p1));

assign add_ln700_13_fu_293_p2 = (trunc_ln700_63_reg_815 + trunc_ln700_64_reg_820);

assign add_ln700_14_fu_508_p2 = ($signed(sext_ln700_21_fu_490_p1) + $signed(sext_ln700_18_fu_462_p1));

assign add_ln700_15_fu_622_p2 = ($signed(sext_ln700_22_fu_618_p1) + $signed(sext_ln700_14_fu_442_p1));

assign add_ln700_16_fu_668_p2 = ($signed(sext_ln700_24_fu_665_p1) + $signed(sext_ln700_15_fu_640_p1));

assign add_ln700_17_fu_681_p2 = ($signed(sext_ln700_26_fu_678_p1) + $signed(sext_ln700_16_fu_643_p1));

assign add_ln700_18_fu_695_p2 = ($signed(sext_ln700_28_fu_691_p1) + $signed(sext_ln215_17_fu_646_p1));

assign add_ln700_19_fu_308_p2 = ($signed(sext_ln700_11_fu_290_p1) + $signed(sext_ln700_12_fu_301_p1));

assign add_ln700_20_fu_318_p2 = ($signed(add_ln700_fu_280_p2) + $signed(add_ln700_19_fu_308_p2));

assign add_ln700_23_fu_338_p2 = (trunc_ln700_69_fu_324_p1 + trunc_ln700_70_fu_328_p1);

assign add_ln700_24_fu_344_p2 = (add_ln700_13_fu_293_p2 + trunc_ln700_68_reg_852);

assign add_ln700_25_fu_349_p2 = (add_ln700_24_fu_344_p2 + trunc_ln700_65_reg_831);

assign add_ln700_26_fu_354_p2 = (add_ln215_fu_297_p2 + trunc_ln700_67_reg_847);

assign add_ln700_27_fu_359_p2 = (add_ln700_26_fu_354_p2 + trunc_ln700_66_reg_836);

assign add_ln700_28_fu_469_p2 = (trunc_ln700_73_reg_879 + trunc_ln700_74_reg_884);

assign add_ln700_29_fu_484_p2 = ($signed(sext_ln700_19_fu_466_p1) + $signed(sext_ln700_20_fu_477_p1));

assign add_ln700_30_fu_494_p2 = ($signed(add_ln700_12_fu_456_p2) + $signed(add_ln700_29_fu_484_p2));

assign add_ln700_33_fu_514_p2 = (trunc_ln700_79_fu_500_p1 + trunc_ln700_80_fu_504_p1);

assign add_ln700_34_fu_520_p2 = (add_ln700_28_fu_469_p2 + trunc_ln700_78_reg_916);

assign add_ln700_35_fu_525_p2 = (add_ln700_34_fu_520_p2 + trunc_ln700_75_reg_895);

assign add_ln700_36_fu_530_p2 = (add_ln215_1_fu_473_p2 + trunc_ln700_77_reg_911);

assign add_ln700_37_fu_535_p2 = (add_ln700_36_fu_530_p2 + trunc_ln700_76_reg_900);

assign add_ln700_76_fu_276_p2 = ($signed(mul_ln1352_12_reg_799) + $signed(mul_ln1352_reg_793));

assign add_ln700_77_fu_304_p2 = ($signed(mul_ln1352_14_reg_841) + $signed(mul_ln1352_13_reg_825));

assign add_ln700_78_fu_452_p2 = ($signed(mul_ln1352_16_reg_863) + $signed(mul_ln1352_15_reg_857));

assign add_ln700_79_fu_480_p2 = ($signed(mul_ln1352_18_reg_905) + $signed(mul_ln1352_17_reg_889));

assign add_ln700_fu_280_p2 = ($signed(sext_ln215_13_fu_270_p1) + $signed(sext_ln700_fu_273_p1));

assign add_ln78_1_fu_418_p2 = (p_Result_4_fu_396_p4 + zext_ln78_1_fu_414_p1);

assign add_ln78_2_fu_634_p2 = ($signed(sext_ln647_fu_628_p1) + $signed(zext_ln78_2_fu_631_p1));

assign add_ln78_3_fu_566_p2 = (p_Result_62_1_fu_544_p4 + zext_ln78_3_fu_562_p1);

assign add_ln78_4_fu_594_p2 = (p_Result_63_1_fu_572_p4 + zext_ln78_4_fu_590_p1);

assign add_ln78_5_fu_656_p2 = ($signed(sext_ln647_1_fu_650_p1) + $signed(zext_ln78_5_fu_653_p1));

assign add_ln78_fu_390_p2 = (p_Result_s_fu_368_p4 + zext_ln78_fu_386_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign mul_ln1352_12_fu_737_p1 = mul_ln1352_12_fu_737_p10;

assign mul_ln1352_12_fu_737_p10 = ipack_1_V_read_int_reg;

assign mul_ln1352_13_fu_745_p1 = mul_ln1352_13_fu_745_p10;

assign mul_ln1352_13_fu_745_p10 = ipack_2_V_read_int_reg;

assign mul_ln1352_14_fu_753_p1 = mul_ln1352_14_fu_753_p10;

assign mul_ln1352_14_fu_753_p10 = ipack_3_V_read_int_reg;

assign mul_ln1352_15_fu_761_p1 = mul_ln1352_15_fu_761_p10;

assign mul_ln1352_15_fu_761_p10 = ipack_4_V_read_int_reg;

assign mul_ln1352_16_fu_769_p1 = mul_ln1352_16_fu_769_p10;

assign mul_ln1352_16_fu_769_p10 = ipack_5_V_read_int_reg;

assign mul_ln1352_17_fu_777_p1 = mul_ln1352_17_fu_777_p10;

assign mul_ln1352_17_fu_777_p10 = ipack_6_V_read_int_reg;

assign mul_ln1352_18_fu_785_p1 = mul_ln1352_18_fu_785_p10;

assign mul_ln1352_18_fu_785_p10 = ipack_7_V_read_int_reg;

assign mul_ln1352_fu_729_p1 = mul_ln1352_fu_729_p10;

assign mul_ln1352_fu_729_p10 = ipack_0_V_read_int_reg;

assign p_Result_4_fu_396_p4 = {{add_ln700_20_fu_318_p2[32:22]}};

assign p_Result_62_1_fu_544_p4 = {{add_ln700_30_fu_494_p2[21:11]}};

assign p_Result_63_1_fu_572_p4 = {{add_ln700_30_fu_494_p2[32:22]}};

assign p_Result_s_fu_368_p4 = {{add_ln700_20_fu_318_p2[21:11]}};

assign sext_ln215_13_fu_270_p1 = mul_ln1352_reg_793;

assign sext_ln215_17_fu_646_p1 = $signed(add_ln78_2_fu_634_p2);

assign sext_ln215_19_fu_446_p1 = mul_ln1352_15_reg_857;

assign sext_ln647_1_fu_650_p1 = $signed(tmp_9_reg_951);

assign sext_ln647_fu_628_p1 = $signed(tmp_reg_931);

assign sext_ln700_10_fu_286_p1 = add_ln700_fu_280_p2;

assign sext_ln700_11_fu_290_p1 = mul_ln1352_13_reg_825;

assign sext_ln700_12_fu_301_p1 = mul_ln1352_14_reg_841;

assign sext_ln700_13_fu_314_p1 = add_ln700_19_fu_308_p2;

assign sext_ln700_14_fu_442_p1 = $signed(trunc_ln647_fu_364_p1);

assign sext_ln700_15_fu_640_p1 = $signed(add_ln78_reg_921);

assign sext_ln700_16_fu_643_p1 = $signed(add_ln78_1_reg_926);

assign sext_ln700_17_fu_449_p1 = mul_ln1352_16_reg_863;

assign sext_ln700_18_fu_462_p1 = add_ln700_12_fu_456_p2;

assign sext_ln700_19_fu_466_p1 = mul_ln1352_17_reg_889;

assign sext_ln700_20_fu_477_p1 = mul_ln1352_18_reg_905;

assign sext_ln700_21_fu_490_p1 = add_ln700_29_fu_484_p2;

assign sext_ln700_22_fu_618_p1 = $signed(trunc_ln647_8_fu_540_p1);

assign sext_ln700_23_fu_662_p1 = $signed(add_ln700_15_reg_961);

assign sext_ln700_24_fu_665_p1 = $signed(add_ln78_3_reg_941);

assign sext_ln700_25_fu_674_p1 = $signed(add_ln700_16_fu_668_p2);

assign sext_ln700_26_fu_678_p1 = $signed(add_ln78_4_reg_946);

assign sext_ln700_27_fu_687_p1 = $signed(add_ln700_17_fu_681_p2);

assign sext_ln700_28_fu_691_p1 = $signed(add_ln78_5_fu_656_p2);

assign sext_ln700_29_fu_701_p1 = $signed(add_ln700_18_fu_695_p2);

assign sext_ln700_fu_273_p1 = mul_ln1352_12_reg_799;

assign tmp_29_fu_378_p3 = add_ln700_27_fu_359_p2[32'd10];

assign tmp_30_fu_406_p3 = add_ln700_25_fu_349_p2[32'd21];

assign tmp_32_fu_554_p3 = add_ln700_37_fu_535_p2[32'd10];

assign tmp_33_fu_582_p3 = add_ln700_35_fu_525_p2[32'd21];

assign trunc_ln647_8_fu_540_p1 = add_ln700_30_fu_494_p2[10:0];

assign trunc_ln647_fu_364_p1 = add_ln700_20_fu_318_p2[10:0];

assign trunc_ln700_62_fu_177_p1 = mul_ln1352_fu_729_p2[10:0];

assign trunc_ln700_63_fu_180_p1 = mul_ln1352_12_fu_737_p2[21:0];

assign trunc_ln700_64_fu_183_p1 = mul_ln1352_fu_729_p2[21:0];

assign trunc_ln700_65_fu_194_p1 = mul_ln1352_13_fu_745_p2[21:0];

assign trunc_ln700_66_fu_197_p1 = mul_ln1352_13_fu_745_p2[10:0];

assign trunc_ln700_67_fu_208_p1 = mul_ln1352_14_fu_753_p2[10:0];

assign trunc_ln700_68_fu_211_p1 = mul_ln1352_14_fu_753_p2[21:0];

assign trunc_ln700_69_fu_324_p1 = add_ln700_76_fu_276_p2[32:0];

assign trunc_ln700_70_fu_328_p1 = add_ln700_77_fu_304_p2[32:0];

assign trunc_ln700_71_fu_230_p1 = mul_ln1352_16_fu_769_p2[10:0];

assign trunc_ln700_72_fu_233_p1 = mul_ln1352_15_fu_761_p2[10:0];

assign trunc_ln700_73_fu_236_p1 = mul_ln1352_16_fu_769_p2[21:0];

assign trunc_ln700_74_fu_239_p1 = mul_ln1352_15_fu_761_p2[21:0];

assign trunc_ln700_75_fu_250_p1 = mul_ln1352_17_fu_777_p2[21:0];

assign trunc_ln700_76_fu_253_p1 = mul_ln1352_17_fu_777_p2[10:0];

assign trunc_ln700_77_fu_264_p1 = mul_ln1352_18_fu_785_p2[10:0];

assign trunc_ln700_78_fu_267_p1 = mul_ln1352_18_fu_785_p2[21:0];

assign trunc_ln700_79_fu_500_p1 = add_ln700_78_fu_452_p2[32:0];

assign trunc_ln700_80_fu_504_p1 = add_ln700_79_fu_480_p2[32:0];

assign trunc_ln700_fu_174_p1 = mul_ln1352_12_fu_737_p2[10:0];

assign zext_ln78_1_fu_414_p1 = tmp_30_fu_406_p3;

assign zext_ln78_2_fu_631_p1 = tmp_31_reg_936;

assign zext_ln78_3_fu_562_p1 = tmp_32_fu_554_p3;

assign zext_ln78_4_fu_590_p1 = tmp_33_fu_582_p3;

assign zext_ln78_5_fu_653_p1 = tmp_34_reg_956;

assign zext_ln78_fu_386_p1 = tmp_29_fu_378_p3;

endmodule //simd_MAC
