// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "simd_mac9_DSP2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic simd_mac9_DSP2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic simd_mac9_DSP2::ap_const_logic_0 = sc_dt::Log_0;
const bool simd_mac9_DSP2::ap_const_boolean_1 = true;
const bool simd_mac9_DSP2::ap_const_boolean_0 = false;
const sc_lv<20> simd_mac9_DSP2::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<32> simd_mac9_DSP2::ap_const_lv32_14 = "10100";
const sc_lv<32> simd_mac9_DSP2::ap_const_lv32_27 = "100111";
const sc_lv<32> simd_mac9_DSP2::ap_const_lv32_13 = "10011";

simd_mac9_DSP2::simd_mac9_DSP2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ultra_net_mul_multde_U104 = new ultra_net_mul_multde<1,1,28,8,36>("ultra_net_mul_multde_U104");
    ultra_net_mul_multde_U104->din0(add_ln68_reg_735);
    ultra_net_mul_multde_U104->din1(mul_ln1352_fu_624_p1);
    ultra_net_mul_multde_U104->dout(mul_ln1352_fu_624_p2);
    ultra_net_mul_multde_U105 = new ultra_net_mul_multde<1,1,28,8,36>("ultra_net_mul_multde_U105");
    ultra_net_mul_multde_U105->din0(add_ln68_4_reg_740);
    ultra_net_mul_multde_U105->din1(mul_ln1352_4_fu_630_p1);
    ultra_net_mul_multde_U105->dout(mul_ln1352_4_fu_630_p2);
    ultra_net_mul_multde_U106 = new ultra_net_mul_multde<1,1,28,8,36>("ultra_net_mul_multde_U106");
    ultra_net_mul_multde_U106->din0(add_ln68_5_reg_745);
    ultra_net_mul_multde_U106->din1(mul_ln1352_5_fu_636_p1);
    ultra_net_mul_multde_U106->dout(mul_ln1352_5_fu_636_p2);
    ultra_net_mul_multde_U107 = new ultra_net_mul_multde<1,1,28,8,36>("ultra_net_mul_multde_U107");
    ultra_net_mul_multde_U107->din0(add_ln68_6_reg_750);
    ultra_net_mul_multde_U107->din1(mul_ln1352_6_fu_642_p1);
    ultra_net_mul_multde_U107->dout(mul_ln1352_6_fu_642_p2);
    ultra_net_mul_multde_U108 = new ultra_net_mul_multde<1,1,28,8,36>("ultra_net_mul_multde_U108");
    ultra_net_mul_multde_U108->din0(add_ln68_7_reg_755);
    ultra_net_mul_multde_U108->din1(mul_ln1352_7_fu_648_p1);
    ultra_net_mul_multde_U108->dout(mul_ln1352_7_fu_648_p2);
    ultra_net_mul_multde_U109 = new ultra_net_mul_multde<1,1,28,8,36>("ultra_net_mul_multde_U109");
    ultra_net_mul_multde_U109->din0(add_ln68_8_reg_760);
    ultra_net_mul_multde_U109->din1(mul_ln1352_8_fu_654_p1);
    ultra_net_mul_multde_U109->dout(mul_ln1352_8_fu_654_p2);
    ultra_net_mul_multde_U110 = new ultra_net_mul_multde<1,1,28,8,36>("ultra_net_mul_multde_U110");
    ultra_net_mul_multde_U110->din0(add_ln68_9_reg_765);
    ultra_net_mul_multde_U110->din1(mul_ln1352_9_fu_661_p1);
    ultra_net_mul_multde_U110->dout(mul_ln1352_9_fu_661_p2);
    ultra_net_mul_multde_U111 = new ultra_net_mul_multde<1,1,28,8,36>("ultra_net_mul_multde_U111");
    ultra_net_mul_multde_U111->din0(add_ln68_10_reg_770);
    ultra_net_mul_multde_U111->din1(mul_ln1352_10_fu_667_p1);
    ultra_net_mul_multde_U111->dout(mul_ln1352_10_fu_667_p2);
    ultra_net_mul_multde_U112 = new ultra_net_mul_multde<1,1,28,8,36>("ultra_net_mul_multde_U112");
    ultra_net_mul_multde_U112->din0(add_ln68_11_reg_820);
    ultra_net_mul_multde_U112->din1(mul_ln1352_11_fu_673_p1);
    ultra_net_mul_multde_U112->dout(mul_ln1352_11_fu_673_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln647_fu_575_p2);
    sensitive << ( trunc_ln700_3_reg_845 );
    sensitive << ( add_ln700_11_fu_558_p2 );

    SC_METHOD(thread_add_ln68_10_fu_372_p2);
    sensitive << ( shl_ln68_s_fu_360_p3 );
    sensitive << ( sext_ln68_7_fu_368_p1 );

    SC_METHOD(thread_add_ln68_11_fu_439_p2);
    sensitive << ( shl_ln68_1_fu_429_p3 );
    sensitive << ( sext_ln68_8_fu_436_p1 );

    SC_METHOD(thread_add_ln68_4_fu_264_p2);
    sensitive << ( shl_ln68_4_fu_252_p3 );
    sensitive << ( sext_ln68_1_fu_260_p1 );

    SC_METHOD(thread_add_ln68_5_fu_282_p2);
    sensitive << ( shl_ln68_5_fu_270_p3 );
    sensitive << ( sext_ln68_2_fu_278_p1 );

    SC_METHOD(thread_add_ln68_6_fu_300_p2);
    sensitive << ( shl_ln68_6_fu_288_p3 );
    sensitive << ( sext_ln68_3_fu_296_p1 );

    SC_METHOD(thread_add_ln68_7_fu_318_p2);
    sensitive << ( shl_ln68_7_fu_306_p3 );
    sensitive << ( sext_ln68_4_fu_314_p1 );

    SC_METHOD(thread_add_ln68_8_fu_336_p2);
    sensitive << ( shl_ln68_8_fu_324_p3 );
    sensitive << ( sext_ln68_5_fu_332_p1 );

    SC_METHOD(thread_add_ln68_9_fu_354_p2);
    sensitive << ( shl_ln68_9_fu_342_p3 );
    sensitive << ( sext_ln68_6_fu_350_p1 );

    SC_METHOD(thread_add_ln68_fu_246_p2);
    sensitive << ( shl_ln_fu_234_p3 );
    sensitive << ( sext_ln68_fu_242_p1 );

    SC_METHOD(thread_add_ln700_10_fu_554_p2);
    sensitive << ( trunc_ln700_1_reg_815_pp0_iter2_reg );
    sensitive << ( trunc_ln700_reg_825 );

    SC_METHOD(thread_add_ln700_11_fu_558_p2);
    sensitive << ( trunc_ln700_2_reg_830 );
    sensitive << ( add_ln700_10_fu_554_p2 );

    SC_METHOD(thread_add_ln700_12_fu_477_p2);
    sensitive << ( add_ln700_fu_451_p2 );
    sensitive << ( add_ln700_3_fu_467_p2 );

    SC_METHOD(thread_add_ln700_3_fu_467_p2);
    sensitive << ( sext_ln68_11_fu_461_p1 );
    sensitive << ( sext_ln700_2_fu_464_p1 );

    SC_METHOD(thread_add_ln700_4_fu_483_p2);
    sensitive << ( sext_ln700_3_fu_473_p1 );
    sensitive << ( sext_ln700_1_fu_457_p1 );

    SC_METHOD(thread_add_ln700_5_fu_509_p2);
    sensitive << ( sext_ln700_4_fu_489_p1 );
    sensitive << ( sext_ln700_5_fu_496_p1 );

    SC_METHOD(thread_add_ln700_6_fu_515_p2);
    sensitive << ( sext_ln68_12_fu_493_p1 );
    sensitive << ( sext_ln700_6_fu_502_p1 );

    SC_METHOD(thread_add_ln700_7_fu_525_p2);
    sensitive << ( sext_ln700_7_fu_521_p1 );
    sensitive << ( sext_ln68_13_fu_499_p1 );

    SC_METHOD(thread_add_ln700_8_fu_539_p2);
    sensitive << ( sext_ln700_8_fu_531_p1 );
    sensitive << ( add_ln700_5_fu_509_p2 );

    SC_METHOD(thread_add_ln700_9_fu_569_p2);
    sensitive << ( sext_ln700_9_fu_563_p1 );
    sensitive << ( sext_ln68_10_fu_566_p1 );

    SC_METHOD(thread_add_ln700_fu_451_p2);
    sensitive << ( sext_ln215_4_fu_445_p1 );
    sensitive << ( sext_ln700_fu_448_p1 );

    SC_METHOD(thread_add_ln78_fu_606_p2);
    sensitive << ( p_Result_s_fu_584_p4 );
    sensitive << ( zext_ln78_fu_602_p1 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( trunc_ln647_fu_580_p1 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_0_int_reg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( add_ln78_fu_606_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_1_int_reg );

    SC_METHOD(thread_mul_ln1352_10_fu_667_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1352_10_fu_667_p10 );

    SC_METHOD(thread_mul_ln1352_10_fu_667_p10);
    sensitive << ( invec_7_V_read_1_reg_695 );

    SC_METHOD(thread_mul_ln1352_11_fu_673_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1352_11_fu_673_p10 );

    SC_METHOD(thread_mul_ln1352_11_fu_673_p10);
    sensitive << ( invec_8_V_read_1_reg_690_pp0_iter1_reg );

    SC_METHOD(thread_mul_ln1352_4_fu_630_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1352_4_fu_630_p10 );

    SC_METHOD(thread_mul_ln1352_4_fu_630_p10);
    sensitive << ( invec_1_V_read_2_reg_725 );

    SC_METHOD(thread_mul_ln1352_5_fu_636_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1352_5_fu_636_p10 );

    SC_METHOD(thread_mul_ln1352_5_fu_636_p10);
    sensitive << ( invec_2_V_read_2_reg_720 );

    SC_METHOD(thread_mul_ln1352_6_fu_642_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1352_6_fu_642_p10 );

    SC_METHOD(thread_mul_ln1352_6_fu_642_p10);
    sensitive << ( invec_3_V_read_2_reg_715 );

    SC_METHOD(thread_mul_ln1352_7_fu_648_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1352_7_fu_648_p10 );

    SC_METHOD(thread_mul_ln1352_7_fu_648_p10);
    sensitive << ( invec_4_V_read_1_reg_710 );

    SC_METHOD(thread_mul_ln1352_8_fu_654_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1352_8_fu_654_p10 );

    SC_METHOD(thread_mul_ln1352_8_fu_654_p10);
    sensitive << ( invec_5_V_read_1_reg_705 );

    SC_METHOD(thread_mul_ln1352_9_fu_661_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1352_9_fu_661_p10 );

    SC_METHOD(thread_mul_ln1352_9_fu_661_p10);
    sensitive << ( invec_6_V_read_1_reg_700 );

    SC_METHOD(thread_mul_ln1352_fu_624_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln1352_fu_624_p10 );

    SC_METHOD(thread_mul_ln1352_fu_624_p10);
    sensitive << ( invec_0_V_read_2_reg_730 );

    SC_METHOD(thread_p_Result_s_fu_584_p4);
    sensitive << ( add_ln700_9_fu_569_p2 );

    SC_METHOD(thread_sext_ln215_4_fu_445_p1);
    sensitive << ( mul_ln1352_reg_775 );

    SC_METHOD(thread_sext_ln68_10_fu_566_p1);
    sensitive << ( mul_ln1352_11_reg_840 );

    SC_METHOD(thread_sext_ln68_11_fu_461_p1);
    sensitive << ( mul_ln1352_5_reg_785 );

    SC_METHOD(thread_sext_ln68_12_fu_493_p1);
    sensitive << ( mul_ln1352_7_reg_795 );

    SC_METHOD(thread_sext_ln68_13_fu_499_p1);
    sensitive << ( mul_ln1352_9_reg_805 );

    SC_METHOD(thread_sext_ln68_1_fu_260_p1);
    sensitive << ( w0vec_1_V_read_int_reg );

    SC_METHOD(thread_sext_ln68_2_fu_278_p1);
    sensitive << ( w0vec_2_V_read_int_reg );

    SC_METHOD(thread_sext_ln68_3_fu_296_p1);
    sensitive << ( w0vec_3_V_read_int_reg );

    SC_METHOD(thread_sext_ln68_4_fu_314_p1);
    sensitive << ( w0vec_4_V_read_int_reg );

    SC_METHOD(thread_sext_ln68_5_fu_332_p1);
    sensitive << ( w0vec_5_V_read_int_reg );

    SC_METHOD(thread_sext_ln68_6_fu_350_p1);
    sensitive << ( w0vec_6_V_read_int_reg );

    SC_METHOD(thread_sext_ln68_7_fu_368_p1);
    sensitive << ( w0vec_7_V_read_int_reg );

    SC_METHOD(thread_sext_ln68_8_fu_436_p1);
    sensitive << ( w0vec_8_V_read_1_reg_685 );

    SC_METHOD(thread_sext_ln68_fu_242_p1);
    sensitive << ( w0vec_0_V_read_int_reg );

    SC_METHOD(thread_sext_ln700_1_fu_457_p1);
    sensitive << ( add_ln700_fu_451_p2 );

    SC_METHOD(thread_sext_ln700_2_fu_464_p1);
    sensitive << ( mul_ln1352_6_reg_790 );

    SC_METHOD(thread_sext_ln700_3_fu_473_p1);
    sensitive << ( add_ln700_3_fu_467_p2 );

    SC_METHOD(thread_sext_ln700_4_fu_489_p1);
    sensitive << ( add_ln700_4_fu_483_p2 );

    SC_METHOD(thread_sext_ln700_5_fu_496_p1);
    sensitive << ( mul_ln1352_8_reg_800 );

    SC_METHOD(thread_sext_ln700_6_fu_502_p1);
    sensitive << ( mul_ln1352_10_reg_810 );

    SC_METHOD(thread_sext_ln700_7_fu_521_p1);
    sensitive << ( add_ln700_6_fu_515_p2 );

    SC_METHOD(thread_sext_ln700_8_fu_531_p1);
    sensitive << ( add_ln700_7_fu_525_p2 );

    SC_METHOD(thread_sext_ln700_9_fu_563_p1);
    sensitive << ( add_ln700_8_reg_835 );

    SC_METHOD(thread_sext_ln700_fu_448_p1);
    sensitive << ( mul_ln1352_4_reg_780 );

    SC_METHOD(thread_shl_ln68_1_fu_429_p3);
    sensitive << ( w1vec_8_V_read_1_reg_680 );

    SC_METHOD(thread_shl_ln68_4_fu_252_p3);
    sensitive << ( w1vec_1_V_read_int_reg );

    SC_METHOD(thread_shl_ln68_5_fu_270_p3);
    sensitive << ( w1vec_2_V_read_int_reg );

    SC_METHOD(thread_shl_ln68_6_fu_288_p3);
    sensitive << ( w1vec_3_V_read_int_reg );

    SC_METHOD(thread_shl_ln68_7_fu_306_p3);
    sensitive << ( w1vec_4_V_read_int_reg );

    SC_METHOD(thread_shl_ln68_8_fu_324_p3);
    sensitive << ( w1vec_5_V_read_int_reg );

    SC_METHOD(thread_shl_ln68_9_fu_342_p3);
    sensitive << ( w1vec_6_V_read_int_reg );

    SC_METHOD(thread_shl_ln68_s_fu_360_p3);
    sensitive << ( w1vec_7_V_read_int_reg );

    SC_METHOD(thread_shl_ln_fu_234_p3);
    sensitive << ( w1vec_0_V_read_int_reg );

    SC_METHOD(thread_tmp_fu_594_p3);
    sensitive << ( add_ln647_fu_575_p2 );

    SC_METHOD(thread_trunc_ln647_fu_580_p1);
    sensitive << ( add_ln700_9_fu_569_p2 );

    SC_METHOD(thread_trunc_ln700_1_fu_426_p1);
    sensitive << ( mul_ln1352_8_fu_654_p2 );

    SC_METHOD(thread_trunc_ln700_2_fu_535_p1);
    sensitive << ( add_ln700_7_fu_525_p2 );

    SC_METHOD(thread_trunc_ln700_3_fu_551_p1);
    sensitive << ( mul_ln1352_11_fu_673_p2 );

    SC_METHOD(thread_trunc_ln700_fu_505_p1);
    sensitive << ( add_ln700_12_fu_477_p2 );

    SC_METHOD(thread_zext_ln78_fu_602_p1);
    sensitive << ( tmp_fu_594_p3 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "simd_mac9_DSP2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, invec_0_V_read, "(port)invec_0_V_read");
    sc_trace(mVcdFile, invec_1_V_read, "(port)invec_1_V_read");
    sc_trace(mVcdFile, invec_2_V_read, "(port)invec_2_V_read");
    sc_trace(mVcdFile, invec_3_V_read, "(port)invec_3_V_read");
    sc_trace(mVcdFile, invec_4_V_read, "(port)invec_4_V_read");
    sc_trace(mVcdFile, invec_5_V_read, "(port)invec_5_V_read");
    sc_trace(mVcdFile, invec_6_V_read, "(port)invec_6_V_read");
    sc_trace(mVcdFile, invec_7_V_read, "(port)invec_7_V_read");
    sc_trace(mVcdFile, invec_8_V_read, "(port)invec_8_V_read");
    sc_trace(mVcdFile, w0vec_0_V_read, "(port)w0vec_0_V_read");
    sc_trace(mVcdFile, w0vec_1_V_read, "(port)w0vec_1_V_read");
    sc_trace(mVcdFile, w0vec_2_V_read, "(port)w0vec_2_V_read");
    sc_trace(mVcdFile, w0vec_3_V_read, "(port)w0vec_3_V_read");
    sc_trace(mVcdFile, w0vec_4_V_read, "(port)w0vec_4_V_read");
    sc_trace(mVcdFile, w0vec_5_V_read, "(port)w0vec_5_V_read");
    sc_trace(mVcdFile, w0vec_6_V_read, "(port)w0vec_6_V_read");
    sc_trace(mVcdFile, w0vec_7_V_read, "(port)w0vec_7_V_read");
    sc_trace(mVcdFile, w0vec_8_V_read, "(port)w0vec_8_V_read");
    sc_trace(mVcdFile, w1vec_0_V_read, "(port)w1vec_0_V_read");
    sc_trace(mVcdFile, w1vec_1_V_read, "(port)w1vec_1_V_read");
    sc_trace(mVcdFile, w1vec_2_V_read, "(port)w1vec_2_V_read");
    sc_trace(mVcdFile, w1vec_3_V_read, "(port)w1vec_3_V_read");
    sc_trace(mVcdFile, w1vec_4_V_read, "(port)w1vec_4_V_read");
    sc_trace(mVcdFile, w1vec_5_V_read, "(port)w1vec_5_V_read");
    sc_trace(mVcdFile, w1vec_6_V_read, "(port)w1vec_6_V_read");
    sc_trace(mVcdFile, w1vec_7_V_read, "(port)w1vec_7_V_read");
    sc_trace(mVcdFile, w1vec_8_V_read, "(port)w1vec_8_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, w1vec_8_V_read_1_reg_680, "w1vec_8_V_read_1_reg_680");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, w0vec_8_V_read_1_reg_685, "w0vec_8_V_read_1_reg_685");
    sc_trace(mVcdFile, invec_8_V_read_1_reg_690, "invec_8_V_read_1_reg_690");
    sc_trace(mVcdFile, invec_8_V_read_1_reg_690_pp0_iter1_reg, "invec_8_V_read_1_reg_690_pp0_iter1_reg");
    sc_trace(mVcdFile, invec_7_V_read_1_reg_695, "invec_7_V_read_1_reg_695");
    sc_trace(mVcdFile, invec_6_V_read_1_reg_700, "invec_6_V_read_1_reg_700");
    sc_trace(mVcdFile, invec_5_V_read_1_reg_705, "invec_5_V_read_1_reg_705");
    sc_trace(mVcdFile, invec_4_V_read_1_reg_710, "invec_4_V_read_1_reg_710");
    sc_trace(mVcdFile, invec_3_V_read_2_reg_715, "invec_3_V_read_2_reg_715");
    sc_trace(mVcdFile, invec_2_V_read_2_reg_720, "invec_2_V_read_2_reg_720");
    sc_trace(mVcdFile, invec_1_V_read_2_reg_725, "invec_1_V_read_2_reg_725");
    sc_trace(mVcdFile, invec_0_V_read_2_reg_730, "invec_0_V_read_2_reg_730");
    sc_trace(mVcdFile, add_ln68_fu_246_p2, "add_ln68_fu_246_p2");
    sc_trace(mVcdFile, add_ln68_reg_735, "add_ln68_reg_735");
    sc_trace(mVcdFile, add_ln68_4_fu_264_p2, "add_ln68_4_fu_264_p2");
    sc_trace(mVcdFile, add_ln68_4_reg_740, "add_ln68_4_reg_740");
    sc_trace(mVcdFile, add_ln68_5_fu_282_p2, "add_ln68_5_fu_282_p2");
    sc_trace(mVcdFile, add_ln68_5_reg_745, "add_ln68_5_reg_745");
    sc_trace(mVcdFile, add_ln68_6_fu_300_p2, "add_ln68_6_fu_300_p2");
    sc_trace(mVcdFile, add_ln68_6_reg_750, "add_ln68_6_reg_750");
    sc_trace(mVcdFile, add_ln68_7_fu_318_p2, "add_ln68_7_fu_318_p2");
    sc_trace(mVcdFile, add_ln68_7_reg_755, "add_ln68_7_reg_755");
    sc_trace(mVcdFile, add_ln68_8_fu_336_p2, "add_ln68_8_fu_336_p2");
    sc_trace(mVcdFile, add_ln68_8_reg_760, "add_ln68_8_reg_760");
    sc_trace(mVcdFile, add_ln68_9_fu_354_p2, "add_ln68_9_fu_354_p2");
    sc_trace(mVcdFile, add_ln68_9_reg_765, "add_ln68_9_reg_765");
    sc_trace(mVcdFile, add_ln68_10_fu_372_p2, "add_ln68_10_fu_372_p2");
    sc_trace(mVcdFile, add_ln68_10_reg_770, "add_ln68_10_reg_770");
    sc_trace(mVcdFile, mul_ln1352_fu_624_p2, "mul_ln1352_fu_624_p2");
    sc_trace(mVcdFile, mul_ln1352_reg_775, "mul_ln1352_reg_775");
    sc_trace(mVcdFile, mul_ln1352_4_fu_630_p2, "mul_ln1352_4_fu_630_p2");
    sc_trace(mVcdFile, mul_ln1352_4_reg_780, "mul_ln1352_4_reg_780");
    sc_trace(mVcdFile, mul_ln1352_5_fu_636_p2, "mul_ln1352_5_fu_636_p2");
    sc_trace(mVcdFile, mul_ln1352_5_reg_785, "mul_ln1352_5_reg_785");
    sc_trace(mVcdFile, mul_ln1352_6_fu_642_p2, "mul_ln1352_6_fu_642_p2");
    sc_trace(mVcdFile, mul_ln1352_6_reg_790, "mul_ln1352_6_reg_790");
    sc_trace(mVcdFile, mul_ln1352_7_fu_648_p2, "mul_ln1352_7_fu_648_p2");
    sc_trace(mVcdFile, mul_ln1352_7_reg_795, "mul_ln1352_7_reg_795");
    sc_trace(mVcdFile, mul_ln1352_8_fu_654_p2, "mul_ln1352_8_fu_654_p2");
    sc_trace(mVcdFile, mul_ln1352_8_reg_800, "mul_ln1352_8_reg_800");
    sc_trace(mVcdFile, mul_ln1352_9_fu_661_p2, "mul_ln1352_9_fu_661_p2");
    sc_trace(mVcdFile, mul_ln1352_9_reg_805, "mul_ln1352_9_reg_805");
    sc_trace(mVcdFile, mul_ln1352_10_fu_667_p2, "mul_ln1352_10_fu_667_p2");
    sc_trace(mVcdFile, mul_ln1352_10_reg_810, "mul_ln1352_10_reg_810");
    sc_trace(mVcdFile, trunc_ln700_1_fu_426_p1, "trunc_ln700_1_fu_426_p1");
    sc_trace(mVcdFile, trunc_ln700_1_reg_815, "trunc_ln700_1_reg_815");
    sc_trace(mVcdFile, trunc_ln700_1_reg_815_pp0_iter2_reg, "trunc_ln700_1_reg_815_pp0_iter2_reg");
    sc_trace(mVcdFile, add_ln68_11_fu_439_p2, "add_ln68_11_fu_439_p2");
    sc_trace(mVcdFile, add_ln68_11_reg_820, "add_ln68_11_reg_820");
    sc_trace(mVcdFile, trunc_ln700_fu_505_p1, "trunc_ln700_fu_505_p1");
    sc_trace(mVcdFile, trunc_ln700_reg_825, "trunc_ln700_reg_825");
    sc_trace(mVcdFile, trunc_ln700_2_fu_535_p1, "trunc_ln700_2_fu_535_p1");
    sc_trace(mVcdFile, trunc_ln700_2_reg_830, "trunc_ln700_2_reg_830");
    sc_trace(mVcdFile, add_ln700_8_fu_539_p2, "add_ln700_8_fu_539_p2");
    sc_trace(mVcdFile, add_ln700_8_reg_835, "add_ln700_8_reg_835");
    sc_trace(mVcdFile, mul_ln1352_11_fu_673_p2, "mul_ln1352_11_fu_673_p2");
    sc_trace(mVcdFile, mul_ln1352_11_reg_840, "mul_ln1352_11_reg_840");
    sc_trace(mVcdFile, trunc_ln700_3_fu_551_p1, "trunc_ln700_3_fu_551_p1");
    sc_trace(mVcdFile, trunc_ln700_3_reg_845, "trunc_ln700_3_reg_845");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, shl_ln_fu_234_p3, "shl_ln_fu_234_p3");
    sc_trace(mVcdFile, sext_ln68_fu_242_p1, "sext_ln68_fu_242_p1");
    sc_trace(mVcdFile, shl_ln68_4_fu_252_p3, "shl_ln68_4_fu_252_p3");
    sc_trace(mVcdFile, sext_ln68_1_fu_260_p1, "sext_ln68_1_fu_260_p1");
    sc_trace(mVcdFile, shl_ln68_5_fu_270_p3, "shl_ln68_5_fu_270_p3");
    sc_trace(mVcdFile, sext_ln68_2_fu_278_p1, "sext_ln68_2_fu_278_p1");
    sc_trace(mVcdFile, shl_ln68_6_fu_288_p3, "shl_ln68_6_fu_288_p3");
    sc_trace(mVcdFile, sext_ln68_3_fu_296_p1, "sext_ln68_3_fu_296_p1");
    sc_trace(mVcdFile, shl_ln68_7_fu_306_p3, "shl_ln68_7_fu_306_p3");
    sc_trace(mVcdFile, sext_ln68_4_fu_314_p1, "sext_ln68_4_fu_314_p1");
    sc_trace(mVcdFile, shl_ln68_8_fu_324_p3, "shl_ln68_8_fu_324_p3");
    sc_trace(mVcdFile, sext_ln68_5_fu_332_p1, "sext_ln68_5_fu_332_p1");
    sc_trace(mVcdFile, shl_ln68_9_fu_342_p3, "shl_ln68_9_fu_342_p3");
    sc_trace(mVcdFile, sext_ln68_6_fu_350_p1, "sext_ln68_6_fu_350_p1");
    sc_trace(mVcdFile, shl_ln68_s_fu_360_p3, "shl_ln68_s_fu_360_p3");
    sc_trace(mVcdFile, sext_ln68_7_fu_368_p1, "sext_ln68_7_fu_368_p1");
    sc_trace(mVcdFile, shl_ln68_1_fu_429_p3, "shl_ln68_1_fu_429_p3");
    sc_trace(mVcdFile, sext_ln68_8_fu_436_p1, "sext_ln68_8_fu_436_p1");
    sc_trace(mVcdFile, sext_ln215_4_fu_445_p1, "sext_ln215_4_fu_445_p1");
    sc_trace(mVcdFile, sext_ln700_fu_448_p1, "sext_ln700_fu_448_p1");
    sc_trace(mVcdFile, add_ln700_fu_451_p2, "add_ln700_fu_451_p2");
    sc_trace(mVcdFile, sext_ln68_11_fu_461_p1, "sext_ln68_11_fu_461_p1");
    sc_trace(mVcdFile, sext_ln700_2_fu_464_p1, "sext_ln700_2_fu_464_p1");
    sc_trace(mVcdFile, add_ln700_3_fu_467_p2, "add_ln700_3_fu_467_p2");
    sc_trace(mVcdFile, sext_ln700_3_fu_473_p1, "sext_ln700_3_fu_473_p1");
    sc_trace(mVcdFile, sext_ln700_1_fu_457_p1, "sext_ln700_1_fu_457_p1");
    sc_trace(mVcdFile, add_ln700_4_fu_483_p2, "add_ln700_4_fu_483_p2");
    sc_trace(mVcdFile, add_ln700_12_fu_477_p2, "add_ln700_12_fu_477_p2");
    sc_trace(mVcdFile, sext_ln700_4_fu_489_p1, "sext_ln700_4_fu_489_p1");
    sc_trace(mVcdFile, sext_ln700_5_fu_496_p1, "sext_ln700_5_fu_496_p1");
    sc_trace(mVcdFile, sext_ln68_12_fu_493_p1, "sext_ln68_12_fu_493_p1");
    sc_trace(mVcdFile, sext_ln700_6_fu_502_p1, "sext_ln700_6_fu_502_p1");
    sc_trace(mVcdFile, add_ln700_6_fu_515_p2, "add_ln700_6_fu_515_p2");
    sc_trace(mVcdFile, sext_ln700_7_fu_521_p1, "sext_ln700_7_fu_521_p1");
    sc_trace(mVcdFile, sext_ln68_13_fu_499_p1, "sext_ln68_13_fu_499_p1");
    sc_trace(mVcdFile, add_ln700_7_fu_525_p2, "add_ln700_7_fu_525_p2");
    sc_trace(mVcdFile, sext_ln700_8_fu_531_p1, "sext_ln700_8_fu_531_p1");
    sc_trace(mVcdFile, add_ln700_5_fu_509_p2, "add_ln700_5_fu_509_p2");
    sc_trace(mVcdFile, add_ln700_10_fu_554_p2, "add_ln700_10_fu_554_p2");
    sc_trace(mVcdFile, sext_ln700_9_fu_563_p1, "sext_ln700_9_fu_563_p1");
    sc_trace(mVcdFile, sext_ln68_10_fu_566_p1, "sext_ln68_10_fu_566_p1");
    sc_trace(mVcdFile, add_ln700_11_fu_558_p2, "add_ln700_11_fu_558_p2");
    sc_trace(mVcdFile, add_ln700_9_fu_569_p2, "add_ln700_9_fu_569_p2");
    sc_trace(mVcdFile, add_ln647_fu_575_p2, "add_ln647_fu_575_p2");
    sc_trace(mVcdFile, tmp_fu_594_p3, "tmp_fu_594_p3");
    sc_trace(mVcdFile, p_Result_s_fu_584_p4, "p_Result_s_fu_584_p4");
    sc_trace(mVcdFile, zext_ln78_fu_602_p1, "zext_ln78_fu_602_p1");
    sc_trace(mVcdFile, trunc_ln647_fu_580_p1, "trunc_ln647_fu_580_p1");
    sc_trace(mVcdFile, add_ln78_fu_606_p2, "add_ln78_fu_606_p2");
    sc_trace(mVcdFile, mul_ln1352_fu_624_p1, "mul_ln1352_fu_624_p1");
    sc_trace(mVcdFile, mul_ln1352_4_fu_630_p1, "mul_ln1352_4_fu_630_p1");
    sc_trace(mVcdFile, mul_ln1352_5_fu_636_p1, "mul_ln1352_5_fu_636_p1");
    sc_trace(mVcdFile, mul_ln1352_6_fu_642_p1, "mul_ln1352_6_fu_642_p1");
    sc_trace(mVcdFile, mul_ln1352_7_fu_648_p1, "mul_ln1352_7_fu_648_p1");
    sc_trace(mVcdFile, mul_ln1352_8_fu_654_p1, "mul_ln1352_8_fu_654_p1");
    sc_trace(mVcdFile, mul_ln1352_9_fu_661_p1, "mul_ln1352_9_fu_661_p1");
    sc_trace(mVcdFile, mul_ln1352_10_fu_667_p1, "mul_ln1352_10_fu_667_p1");
    sc_trace(mVcdFile, mul_ln1352_11_fu_673_p1, "mul_ln1352_11_fu_673_p1");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, invec_0_V_read_int_reg, "invec_0_V_read_int_reg");
    sc_trace(mVcdFile, invec_1_V_read_int_reg, "invec_1_V_read_int_reg");
    sc_trace(mVcdFile, invec_2_V_read_int_reg, "invec_2_V_read_int_reg");
    sc_trace(mVcdFile, invec_3_V_read_int_reg, "invec_3_V_read_int_reg");
    sc_trace(mVcdFile, invec_4_V_read_int_reg, "invec_4_V_read_int_reg");
    sc_trace(mVcdFile, invec_5_V_read_int_reg, "invec_5_V_read_int_reg");
    sc_trace(mVcdFile, invec_6_V_read_int_reg, "invec_6_V_read_int_reg");
    sc_trace(mVcdFile, invec_7_V_read_int_reg, "invec_7_V_read_int_reg");
    sc_trace(mVcdFile, invec_8_V_read_int_reg, "invec_8_V_read_int_reg");
    sc_trace(mVcdFile, w0vec_0_V_read_int_reg, "w0vec_0_V_read_int_reg");
    sc_trace(mVcdFile, w0vec_1_V_read_int_reg, "w0vec_1_V_read_int_reg");
    sc_trace(mVcdFile, w0vec_2_V_read_int_reg, "w0vec_2_V_read_int_reg");
    sc_trace(mVcdFile, w0vec_3_V_read_int_reg, "w0vec_3_V_read_int_reg");
    sc_trace(mVcdFile, w0vec_4_V_read_int_reg, "w0vec_4_V_read_int_reg");
    sc_trace(mVcdFile, w0vec_5_V_read_int_reg, "w0vec_5_V_read_int_reg");
    sc_trace(mVcdFile, w0vec_6_V_read_int_reg, "w0vec_6_V_read_int_reg");
    sc_trace(mVcdFile, w0vec_7_V_read_int_reg, "w0vec_7_V_read_int_reg");
    sc_trace(mVcdFile, w0vec_8_V_read_int_reg, "w0vec_8_V_read_int_reg");
    sc_trace(mVcdFile, w1vec_0_V_read_int_reg, "w1vec_0_V_read_int_reg");
    sc_trace(mVcdFile, w1vec_1_V_read_int_reg, "w1vec_1_V_read_int_reg");
    sc_trace(mVcdFile, w1vec_2_V_read_int_reg, "w1vec_2_V_read_int_reg");
    sc_trace(mVcdFile, w1vec_3_V_read_int_reg, "w1vec_3_V_read_int_reg");
    sc_trace(mVcdFile, w1vec_4_V_read_int_reg, "w1vec_4_V_read_int_reg");
    sc_trace(mVcdFile, w1vec_5_V_read_int_reg, "w1vec_5_V_read_int_reg");
    sc_trace(mVcdFile, w1vec_6_V_read_int_reg, "w1vec_6_V_read_int_reg");
    sc_trace(mVcdFile, w1vec_7_V_read_int_reg, "w1vec_7_V_read_int_reg");
    sc_trace(mVcdFile, w1vec_8_V_read_int_reg, "w1vec_8_V_read_int_reg");
    sc_trace(mVcdFile, ap_return_0_int_reg, "ap_return_0_int_reg");
    sc_trace(mVcdFile, ap_return_1_int_reg, "ap_return_1_int_reg");
    sc_trace(mVcdFile, mul_ln1352_10_fu_667_p10, "mul_ln1352_10_fu_667_p10");
    sc_trace(mVcdFile, mul_ln1352_11_fu_673_p10, "mul_ln1352_11_fu_673_p10");
    sc_trace(mVcdFile, mul_ln1352_4_fu_630_p10, "mul_ln1352_4_fu_630_p10");
    sc_trace(mVcdFile, mul_ln1352_5_fu_636_p10, "mul_ln1352_5_fu_636_p10");
    sc_trace(mVcdFile, mul_ln1352_6_fu_642_p10, "mul_ln1352_6_fu_642_p10");
    sc_trace(mVcdFile, mul_ln1352_7_fu_648_p10, "mul_ln1352_7_fu_648_p10");
    sc_trace(mVcdFile, mul_ln1352_8_fu_654_p10, "mul_ln1352_8_fu_654_p10");
    sc_trace(mVcdFile, mul_ln1352_9_fu_661_p10, "mul_ln1352_9_fu_661_p10");
    sc_trace(mVcdFile, mul_ln1352_fu_624_p10, "mul_ln1352_fu_624_p10");
#endif

    }
}

simd_mac9_DSP2::~simd_mac9_DSP2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete ultra_net_mul_multde_U104;
    delete ultra_net_mul_multde_U105;
    delete ultra_net_mul_multde_U106;
    delete ultra_net_mul_multde_U107;
    delete ultra_net_mul_multde_U108;
    delete ultra_net_mul_multde_U109;
    delete ultra_net_mul_multde_U110;
    delete ultra_net_mul_multde_U111;
    delete ultra_net_mul_multde_U112;
}

void simd_mac9_DSP2::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1))) {
        add_ln68_10_reg_770 = add_ln68_10_fu_372_p2.read();
        add_ln68_11_reg_820 = add_ln68_11_fu_439_p2.read();
        add_ln68_4_reg_740 = add_ln68_4_fu_264_p2.read();
        add_ln68_5_reg_745 = add_ln68_5_fu_282_p2.read();
        add_ln68_6_reg_750 = add_ln68_6_fu_300_p2.read();
        add_ln68_7_reg_755 = add_ln68_7_fu_318_p2.read();
        add_ln68_8_reg_760 = add_ln68_8_fu_336_p2.read();
        add_ln68_9_reg_765 = add_ln68_9_fu_354_p2.read();
        add_ln68_reg_735 = add_ln68_fu_246_p2.read();
        add_ln700_8_reg_835 = add_ln700_8_fu_539_p2.read();
        invec_0_V_read_2_reg_730 = invec_0_V_read_int_reg.read();
        invec_1_V_read_2_reg_725 = invec_1_V_read_int_reg.read();
        invec_2_V_read_2_reg_720 = invec_2_V_read_int_reg.read();
        invec_3_V_read_2_reg_715 = invec_3_V_read_int_reg.read();
        invec_4_V_read_1_reg_710 = invec_4_V_read_int_reg.read();
        invec_5_V_read_1_reg_705 = invec_5_V_read_int_reg.read();
        invec_6_V_read_1_reg_700 = invec_6_V_read_int_reg.read();
        invec_7_V_read_1_reg_695 = invec_7_V_read_int_reg.read();
        invec_8_V_read_1_reg_690 = invec_8_V_read_int_reg.read();
        invec_8_V_read_1_reg_690_pp0_iter1_reg = invec_8_V_read_1_reg_690.read();
        mul_ln1352_10_reg_810 = mul_ln1352_10_fu_667_p2.read();
        mul_ln1352_11_reg_840 = mul_ln1352_11_fu_673_p2.read();
        mul_ln1352_4_reg_780 = mul_ln1352_4_fu_630_p2.read();
        mul_ln1352_5_reg_785 = mul_ln1352_5_fu_636_p2.read();
        mul_ln1352_6_reg_790 = mul_ln1352_6_fu_642_p2.read();
        mul_ln1352_7_reg_795 = mul_ln1352_7_fu_648_p2.read();
        mul_ln1352_8_reg_800 = mul_ln1352_8_fu_654_p2.read();
        mul_ln1352_9_reg_805 = mul_ln1352_9_fu_661_p2.read();
        mul_ln1352_reg_775 = mul_ln1352_fu_624_p2.read();
        trunc_ln700_1_reg_815 = trunc_ln700_1_fu_426_p1.read();
        trunc_ln700_1_reg_815_pp0_iter2_reg = trunc_ln700_1_reg_815.read();
        trunc_ln700_2_reg_830 = trunc_ln700_2_fu_535_p1.read();
        trunc_ln700_3_reg_845 = trunc_ln700_3_fu_551_p1.read();
        trunc_ln700_reg_825 = trunc_ln700_fu_505_p1.read();
        w0vec_8_V_read_1_reg_685 = w0vec_8_V_read_int_reg.read();
        w1vec_8_V_read_1_reg_680 = w1vec_8_V_read_int_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0_int_reg = trunc_ln647_fu_580_p1.read();
        ap_return_1_int_reg = add_ln78_fu_606_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read())) {
        invec_0_V_read_int_reg = invec_0_V_read.read();
        invec_1_V_read_int_reg = invec_1_V_read.read();
        invec_2_V_read_int_reg = invec_2_V_read.read();
        invec_3_V_read_int_reg = invec_3_V_read.read();
        invec_4_V_read_int_reg = invec_4_V_read.read();
        invec_5_V_read_int_reg = invec_5_V_read.read();
        invec_6_V_read_int_reg = invec_6_V_read.read();
        invec_7_V_read_int_reg = invec_7_V_read.read();
        invec_8_V_read_int_reg = invec_8_V_read.read();
        w0vec_0_V_read_int_reg = w0vec_0_V_read.read();
        w0vec_1_V_read_int_reg = w0vec_1_V_read.read();
        w0vec_2_V_read_int_reg = w0vec_2_V_read.read();
        w0vec_3_V_read_int_reg = w0vec_3_V_read.read();
        w0vec_4_V_read_int_reg = w0vec_4_V_read.read();
        w0vec_5_V_read_int_reg = w0vec_5_V_read.read();
        w0vec_6_V_read_int_reg = w0vec_6_V_read.read();
        w0vec_7_V_read_int_reg = w0vec_7_V_read.read();
        w0vec_8_V_read_int_reg = w0vec_8_V_read.read();
        w1vec_0_V_read_int_reg = w1vec_0_V_read.read();
        w1vec_1_V_read_int_reg = w1vec_1_V_read.read();
        w1vec_2_V_read_int_reg = w1vec_2_V_read.read();
        w1vec_3_V_read_int_reg = w1vec_3_V_read.read();
        w1vec_4_V_read_int_reg = w1vec_4_V_read.read();
        w1vec_5_V_read_int_reg = w1vec_5_V_read.read();
        w1vec_6_V_read_int_reg = w1vec_6_V_read.read();
        w1vec_7_V_read_int_reg = w1vec_7_V_read.read();
        w1vec_8_V_read_int_reg = w1vec_8_V_read.read();
    }
}

void simd_mac9_DSP2::thread_add_ln647_fu_575_p2() {
    add_ln647_fu_575_p2 = (!add_ln700_11_fu_558_p2.read().is_01() || !trunc_ln700_3_reg_845.read().is_01())? sc_lv<20>(): (sc_biguint<20>(add_ln700_11_fu_558_p2.read()) + sc_biguint<20>(trunc_ln700_3_reg_845.read()));
}

void simd_mac9_DSP2::thread_add_ln68_10_fu_372_p2() {
    add_ln68_10_fu_372_p2 = (!shl_ln68_s_fu_360_p3.read().is_01() || !sext_ln68_7_fu_368_p1.read().is_01())? sc_lv<28>(): (sc_biguint<28>(shl_ln68_s_fu_360_p3.read()) + sc_bigint<28>(sext_ln68_7_fu_368_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln68_11_fu_439_p2() {
    add_ln68_11_fu_439_p2 = (!shl_ln68_1_fu_429_p3.read().is_01() || !sext_ln68_8_fu_436_p1.read().is_01())? sc_lv<28>(): (sc_biguint<28>(shl_ln68_1_fu_429_p3.read()) + sc_bigint<28>(sext_ln68_8_fu_436_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln68_4_fu_264_p2() {
    add_ln68_4_fu_264_p2 = (!shl_ln68_4_fu_252_p3.read().is_01() || !sext_ln68_1_fu_260_p1.read().is_01())? sc_lv<28>(): (sc_biguint<28>(shl_ln68_4_fu_252_p3.read()) + sc_bigint<28>(sext_ln68_1_fu_260_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln68_5_fu_282_p2() {
    add_ln68_5_fu_282_p2 = (!shl_ln68_5_fu_270_p3.read().is_01() || !sext_ln68_2_fu_278_p1.read().is_01())? sc_lv<28>(): (sc_biguint<28>(shl_ln68_5_fu_270_p3.read()) + sc_bigint<28>(sext_ln68_2_fu_278_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln68_6_fu_300_p2() {
    add_ln68_6_fu_300_p2 = (!shl_ln68_6_fu_288_p3.read().is_01() || !sext_ln68_3_fu_296_p1.read().is_01())? sc_lv<28>(): (sc_biguint<28>(shl_ln68_6_fu_288_p3.read()) + sc_bigint<28>(sext_ln68_3_fu_296_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln68_7_fu_318_p2() {
    add_ln68_7_fu_318_p2 = (!shl_ln68_7_fu_306_p3.read().is_01() || !sext_ln68_4_fu_314_p1.read().is_01())? sc_lv<28>(): (sc_biguint<28>(shl_ln68_7_fu_306_p3.read()) + sc_bigint<28>(sext_ln68_4_fu_314_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln68_8_fu_336_p2() {
    add_ln68_8_fu_336_p2 = (!shl_ln68_8_fu_324_p3.read().is_01() || !sext_ln68_5_fu_332_p1.read().is_01())? sc_lv<28>(): (sc_biguint<28>(shl_ln68_8_fu_324_p3.read()) + sc_bigint<28>(sext_ln68_5_fu_332_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln68_9_fu_354_p2() {
    add_ln68_9_fu_354_p2 = (!shl_ln68_9_fu_342_p3.read().is_01() || !sext_ln68_6_fu_350_p1.read().is_01())? sc_lv<28>(): (sc_biguint<28>(shl_ln68_9_fu_342_p3.read()) + sc_bigint<28>(sext_ln68_6_fu_350_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln68_fu_246_p2() {
    add_ln68_fu_246_p2 = (!shl_ln_fu_234_p3.read().is_01() || !sext_ln68_fu_242_p1.read().is_01())? sc_lv<28>(): (sc_biguint<28>(shl_ln_fu_234_p3.read()) + sc_bigint<28>(sext_ln68_fu_242_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln700_10_fu_554_p2() {
    add_ln700_10_fu_554_p2 = (!trunc_ln700_1_reg_815_pp0_iter2_reg.read().is_01() || !trunc_ln700_reg_825.read().is_01())? sc_lv<20>(): (sc_biguint<20>(trunc_ln700_1_reg_815_pp0_iter2_reg.read()) + sc_biguint<20>(trunc_ln700_reg_825.read()));
}

void simd_mac9_DSP2::thread_add_ln700_11_fu_558_p2() {
    add_ln700_11_fu_558_p2 = (!add_ln700_10_fu_554_p2.read().is_01() || !trunc_ln700_2_reg_830.read().is_01())? sc_lv<20>(): (sc_biguint<20>(add_ln700_10_fu_554_p2.read()) + sc_biguint<20>(trunc_ln700_2_reg_830.read()));
}

void simd_mac9_DSP2::thread_add_ln700_12_fu_477_p2() {
    add_ln700_12_fu_477_p2 = (!add_ln700_fu_451_p2.read().is_01() || !add_ln700_3_fu_467_p2.read().is_01())? sc_lv<37>(): (sc_bigint<37>(add_ln700_fu_451_p2.read()) + sc_bigint<37>(add_ln700_3_fu_467_p2.read()));
}

void simd_mac9_DSP2::thread_add_ln700_3_fu_467_p2() {
    add_ln700_3_fu_467_p2 = (!sext_ln68_11_fu_461_p1.read().is_01() || !sext_ln700_2_fu_464_p1.read().is_01())? sc_lv<37>(): (sc_bigint<37>(sext_ln68_11_fu_461_p1.read()) + sc_bigint<37>(sext_ln700_2_fu_464_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln700_4_fu_483_p2() {
    add_ln700_4_fu_483_p2 = (!sext_ln700_3_fu_473_p1.read().is_01() || !sext_ln700_1_fu_457_p1.read().is_01())? sc_lv<38>(): (sc_bigint<38>(sext_ln700_3_fu_473_p1.read()) + sc_bigint<38>(sext_ln700_1_fu_457_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln700_5_fu_509_p2() {
    add_ln700_5_fu_509_p2 = (!sext_ln700_4_fu_489_p1.read().is_01() || !sext_ln700_5_fu_496_p1.read().is_01())? sc_lv<39>(): (sc_bigint<39>(sext_ln700_4_fu_489_p1.read()) + sc_bigint<39>(sext_ln700_5_fu_496_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln700_6_fu_515_p2() {
    add_ln700_6_fu_515_p2 = (!sext_ln68_12_fu_493_p1.read().is_01() || !sext_ln700_6_fu_502_p1.read().is_01())? sc_lv<37>(): (sc_bigint<37>(sext_ln68_12_fu_493_p1.read()) + sc_bigint<37>(sext_ln700_6_fu_502_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln700_7_fu_525_p2() {
    add_ln700_7_fu_525_p2 = (!sext_ln700_7_fu_521_p1.read().is_01() || !sext_ln68_13_fu_499_p1.read().is_01())? sc_lv<38>(): (sc_bigint<38>(sext_ln700_7_fu_521_p1.read()) + sc_bigint<38>(sext_ln68_13_fu_499_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln700_8_fu_539_p2() {
    add_ln700_8_fu_539_p2 = (!sext_ln700_8_fu_531_p1.read().is_01() || !add_ln700_5_fu_509_p2.read().is_01())? sc_lv<39>(): (sc_bigint<39>(sext_ln700_8_fu_531_p1.read()) + sc_biguint<39>(add_ln700_5_fu_509_p2.read()));
}

void simd_mac9_DSP2::thread_add_ln700_9_fu_569_p2() {
    add_ln700_9_fu_569_p2 = (!sext_ln700_9_fu_563_p1.read().is_01() || !sext_ln68_10_fu_566_p1.read().is_01())? sc_lv<40>(): (sc_bigint<40>(sext_ln700_9_fu_563_p1.read()) + sc_bigint<40>(sext_ln68_10_fu_566_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln700_fu_451_p2() {
    add_ln700_fu_451_p2 = (!sext_ln215_4_fu_445_p1.read().is_01() || !sext_ln700_fu_448_p1.read().is_01())? sc_lv<37>(): (sc_bigint<37>(sext_ln215_4_fu_445_p1.read()) + sc_bigint<37>(sext_ln700_fu_448_p1.read()));
}

void simd_mac9_DSP2::thread_add_ln78_fu_606_p2() {
    add_ln78_fu_606_p2 = (!p_Result_s_fu_584_p4.read().is_01() || !zext_ln78_fu_602_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_Result_s_fu_584_p4.read()) + sc_biguint<20>(zext_ln78_fu_602_p1.read()));
}

void simd_mac9_DSP2::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void simd_mac9_DSP2::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void simd_mac9_DSP2::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void simd_mac9_DSP2::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void simd_mac9_DSP2::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void simd_mac9_DSP2::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void simd_mac9_DSP2::thread_ap_return_0() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_0 = ap_return_0_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0 = trunc_ln647_fu_580_p1.read();
    }
}

void simd_mac9_DSP2::thread_ap_return_1() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_1 = ap_return_1_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_1 = add_ln78_fu_606_p2.read();
    }
}

void simd_mac9_DSP2::thread_mul_ln1352_10_fu_667_p1() {
    mul_ln1352_10_fu_667_p1 =  (sc_lv<8>) (mul_ln1352_10_fu_667_p10.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_10_fu_667_p10() {
    mul_ln1352_10_fu_667_p10 = esl_zext<36,8>(invec_7_V_read_1_reg_695.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_11_fu_673_p1() {
    mul_ln1352_11_fu_673_p1 =  (sc_lv<8>) (mul_ln1352_11_fu_673_p10.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_11_fu_673_p10() {
    mul_ln1352_11_fu_673_p10 = esl_zext<36,8>(invec_8_V_read_1_reg_690_pp0_iter1_reg.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_4_fu_630_p1() {
    mul_ln1352_4_fu_630_p1 =  (sc_lv<8>) (mul_ln1352_4_fu_630_p10.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_4_fu_630_p10() {
    mul_ln1352_4_fu_630_p10 = esl_zext<36,8>(invec_1_V_read_2_reg_725.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_5_fu_636_p1() {
    mul_ln1352_5_fu_636_p1 =  (sc_lv<8>) (mul_ln1352_5_fu_636_p10.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_5_fu_636_p10() {
    mul_ln1352_5_fu_636_p10 = esl_zext<36,8>(invec_2_V_read_2_reg_720.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_6_fu_642_p1() {
    mul_ln1352_6_fu_642_p1 =  (sc_lv<8>) (mul_ln1352_6_fu_642_p10.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_6_fu_642_p10() {
    mul_ln1352_6_fu_642_p10 = esl_zext<36,8>(invec_3_V_read_2_reg_715.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_7_fu_648_p1() {
    mul_ln1352_7_fu_648_p1 =  (sc_lv<8>) (mul_ln1352_7_fu_648_p10.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_7_fu_648_p10() {
    mul_ln1352_7_fu_648_p10 = esl_zext<36,8>(invec_4_V_read_1_reg_710.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_8_fu_654_p1() {
    mul_ln1352_8_fu_654_p1 =  (sc_lv<8>) (mul_ln1352_8_fu_654_p10.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_8_fu_654_p10() {
    mul_ln1352_8_fu_654_p10 = esl_zext<36,8>(invec_5_V_read_1_reg_705.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_9_fu_661_p1() {
    mul_ln1352_9_fu_661_p1 =  (sc_lv<8>) (mul_ln1352_9_fu_661_p10.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_9_fu_661_p10() {
    mul_ln1352_9_fu_661_p10 = esl_zext<36,8>(invec_6_V_read_1_reg_700.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_fu_624_p1() {
    mul_ln1352_fu_624_p1 =  (sc_lv<8>) (mul_ln1352_fu_624_p10.read());
}

void simd_mac9_DSP2::thread_mul_ln1352_fu_624_p10() {
    mul_ln1352_fu_624_p10 = esl_zext<36,8>(invec_0_V_read_2_reg_730.read());
}

void simd_mac9_DSP2::thread_p_Result_s_fu_584_p4() {
    p_Result_s_fu_584_p4 = add_ln700_9_fu_569_p2.read().range(39, 20);
}

void simd_mac9_DSP2::thread_sext_ln215_4_fu_445_p1() {
    sext_ln215_4_fu_445_p1 = esl_sext<37,36>(mul_ln1352_reg_775.read());
}

void simd_mac9_DSP2::thread_sext_ln68_10_fu_566_p1() {
    sext_ln68_10_fu_566_p1 = esl_sext<40,36>(mul_ln1352_11_reg_840.read());
}

void simd_mac9_DSP2::thread_sext_ln68_11_fu_461_p1() {
    sext_ln68_11_fu_461_p1 = esl_sext<37,36>(mul_ln1352_5_reg_785.read());
}

void simd_mac9_DSP2::thread_sext_ln68_12_fu_493_p1() {
    sext_ln68_12_fu_493_p1 = esl_sext<37,36>(mul_ln1352_7_reg_795.read());
}

void simd_mac9_DSP2::thread_sext_ln68_13_fu_499_p1() {
    sext_ln68_13_fu_499_p1 = esl_sext<38,36>(mul_ln1352_9_reg_805.read());
}

void simd_mac9_DSP2::thread_sext_ln68_1_fu_260_p1() {
    sext_ln68_1_fu_260_p1 = esl_sext<28,8>(w0vec_1_V_read_int_reg.read());
}

void simd_mac9_DSP2::thread_sext_ln68_2_fu_278_p1() {
    sext_ln68_2_fu_278_p1 = esl_sext<28,8>(w0vec_2_V_read_int_reg.read());
}

void simd_mac9_DSP2::thread_sext_ln68_3_fu_296_p1() {
    sext_ln68_3_fu_296_p1 = esl_sext<28,8>(w0vec_3_V_read_int_reg.read());
}

void simd_mac9_DSP2::thread_sext_ln68_4_fu_314_p1() {
    sext_ln68_4_fu_314_p1 = esl_sext<28,8>(w0vec_4_V_read_int_reg.read());
}

void simd_mac9_DSP2::thread_sext_ln68_5_fu_332_p1() {
    sext_ln68_5_fu_332_p1 = esl_sext<28,8>(w0vec_5_V_read_int_reg.read());
}

void simd_mac9_DSP2::thread_sext_ln68_6_fu_350_p1() {
    sext_ln68_6_fu_350_p1 = esl_sext<28,8>(w0vec_6_V_read_int_reg.read());
}

void simd_mac9_DSP2::thread_sext_ln68_7_fu_368_p1() {
    sext_ln68_7_fu_368_p1 = esl_sext<28,8>(w0vec_7_V_read_int_reg.read());
}

void simd_mac9_DSP2::thread_sext_ln68_8_fu_436_p1() {
    sext_ln68_8_fu_436_p1 = esl_sext<28,8>(w0vec_8_V_read_1_reg_685.read());
}

void simd_mac9_DSP2::thread_sext_ln68_fu_242_p1() {
    sext_ln68_fu_242_p1 = esl_sext<28,8>(w0vec_0_V_read_int_reg.read());
}

void simd_mac9_DSP2::thread_sext_ln700_1_fu_457_p1() {
    sext_ln700_1_fu_457_p1 = esl_sext<38,37>(add_ln700_fu_451_p2.read());
}

void simd_mac9_DSP2::thread_sext_ln700_2_fu_464_p1() {
    sext_ln700_2_fu_464_p1 = esl_sext<37,36>(mul_ln1352_6_reg_790.read());
}

void simd_mac9_DSP2::thread_sext_ln700_3_fu_473_p1() {
    sext_ln700_3_fu_473_p1 = esl_sext<38,37>(add_ln700_3_fu_467_p2.read());
}

void simd_mac9_DSP2::thread_sext_ln700_4_fu_489_p1() {
    sext_ln700_4_fu_489_p1 = esl_sext<39,38>(add_ln700_4_fu_483_p2.read());
}

void simd_mac9_DSP2::thread_sext_ln700_5_fu_496_p1() {
    sext_ln700_5_fu_496_p1 = esl_sext<39,36>(mul_ln1352_8_reg_800.read());
}

void simd_mac9_DSP2::thread_sext_ln700_6_fu_502_p1() {
    sext_ln700_6_fu_502_p1 = esl_sext<37,36>(mul_ln1352_10_reg_810.read());
}

void simd_mac9_DSP2::thread_sext_ln700_7_fu_521_p1() {
    sext_ln700_7_fu_521_p1 = esl_sext<38,37>(add_ln700_6_fu_515_p2.read());
}

void simd_mac9_DSP2::thread_sext_ln700_8_fu_531_p1() {
    sext_ln700_8_fu_531_p1 = esl_sext<39,38>(add_ln700_7_fu_525_p2.read());
}

void simd_mac9_DSP2::thread_sext_ln700_9_fu_563_p1() {
    sext_ln700_9_fu_563_p1 = esl_sext<40,39>(add_ln700_8_reg_835.read());
}

void simd_mac9_DSP2::thread_sext_ln700_fu_448_p1() {
    sext_ln700_fu_448_p1 = esl_sext<37,36>(mul_ln1352_4_reg_780.read());
}

void simd_mac9_DSP2::thread_shl_ln68_1_fu_429_p3() {
    shl_ln68_1_fu_429_p3 = esl_concat<8,20>(w1vec_8_V_read_1_reg_680.read(), ap_const_lv20_0);
}

void simd_mac9_DSP2::thread_shl_ln68_4_fu_252_p3() {
    shl_ln68_4_fu_252_p3 = esl_concat<8,20>(w1vec_1_V_read_int_reg.read(), ap_const_lv20_0);
}

void simd_mac9_DSP2::thread_shl_ln68_5_fu_270_p3() {
    shl_ln68_5_fu_270_p3 = esl_concat<8,20>(w1vec_2_V_read_int_reg.read(), ap_const_lv20_0);
}

void simd_mac9_DSP2::thread_shl_ln68_6_fu_288_p3() {
    shl_ln68_6_fu_288_p3 = esl_concat<8,20>(w1vec_3_V_read_int_reg.read(), ap_const_lv20_0);
}

void simd_mac9_DSP2::thread_shl_ln68_7_fu_306_p3() {
    shl_ln68_7_fu_306_p3 = esl_concat<8,20>(w1vec_4_V_read_int_reg.read(), ap_const_lv20_0);
}

void simd_mac9_DSP2::thread_shl_ln68_8_fu_324_p3() {
    shl_ln68_8_fu_324_p3 = esl_concat<8,20>(w1vec_5_V_read_int_reg.read(), ap_const_lv20_0);
}

void simd_mac9_DSP2::thread_shl_ln68_9_fu_342_p3() {
    shl_ln68_9_fu_342_p3 = esl_concat<8,20>(w1vec_6_V_read_int_reg.read(), ap_const_lv20_0);
}

void simd_mac9_DSP2::thread_shl_ln68_s_fu_360_p3() {
    shl_ln68_s_fu_360_p3 = esl_concat<8,20>(w1vec_7_V_read_int_reg.read(), ap_const_lv20_0);
}

void simd_mac9_DSP2::thread_shl_ln_fu_234_p3() {
    shl_ln_fu_234_p3 = esl_concat<8,20>(w1vec_0_V_read_int_reg.read(), ap_const_lv20_0);
}

void simd_mac9_DSP2::thread_tmp_fu_594_p3() {
    tmp_fu_594_p3 = add_ln647_fu_575_p2.read().range(19, 19);
}

void simd_mac9_DSP2::thread_trunc_ln647_fu_580_p1() {
    trunc_ln647_fu_580_p1 = add_ln700_9_fu_569_p2.read().range(20-1, 0);
}

void simd_mac9_DSP2::thread_trunc_ln700_1_fu_426_p1() {
    trunc_ln700_1_fu_426_p1 = mul_ln1352_8_fu_654_p2.read().range(20-1, 0);
}

void simd_mac9_DSP2::thread_trunc_ln700_2_fu_535_p1() {
    trunc_ln700_2_fu_535_p1 = add_ln700_7_fu_525_p2.read().range(20-1, 0);
}

void simd_mac9_DSP2::thread_trunc_ln700_3_fu_551_p1() {
    trunc_ln700_3_fu_551_p1 = mul_ln1352_11_fu_673_p2.read().range(20-1, 0);
}

void simd_mac9_DSP2::thread_trunc_ln700_fu_505_p1() {
    trunc_ln700_fu_505_p1 = add_ln700_12_fu_477_p2.read().range(20-1, 0);
}

void simd_mac9_DSP2::thread_zext_ln78_fu_602_p1() {
    zext_ln78_fu_602_p1 = esl_zext<20,1>(tmp_fu_594_p3.read());
}

}

