// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "stream_out_data_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic stream_out_data_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic stream_out_data_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> stream_out_data_1::ap_ST_fsm_state1 = "1";
const sc_lv<3> stream_out_data_1::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> stream_out_data_1::ap_ST_fsm_state6 = "100";
const bool stream_out_data_1::ap_const_boolean_1 = true;
const sc_lv<32> stream_out_data_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool stream_out_data_1::ap_const_boolean_0 = false;
const sc_lv<1> stream_out_data_1::ap_const_lv1_0 = "0";
const sc_lv<32> stream_out_data_1::ap_const_lv32_1 = "1";
const sc_lv<1> stream_out_data_1::ap_const_lv1_1 = "1";
const sc_lv<12> stream_out_data_1::ap_const_lv12_0 = "000000000000";
const sc_lv<8> stream_out_data_1::ap_const_lv8_0 = "00000000";
const sc_lv<9> stream_out_data_1::ap_const_lv9_0 = "000000000";
const sc_lv<11> stream_out_data_1::ap_const_lv11_7FF = "11111111111";
const sc_lv<12> stream_out_data_1::ap_const_lv12_F60 = "111101100000";
const sc_lv<12> stream_out_data_1::ap_const_lv12_1 = "1";
const sc_lv<9> stream_out_data_1::ap_const_lv9_1EC = "111101100";
const sc_lv<32> stream_out_data_1::ap_const_lv32_2 = "10";
const sc_lv<32> stream_out_data_1::ap_const_lv32_3 = "11";
const sc_lv<32> stream_out_data_1::ap_const_lv32_A = "1010";
const sc_lv<11> stream_out_data_1::ap_const_lv11_27 = "100111";
const sc_lv<9> stream_out_data_1::ap_const_lv9_1EB = "111101011";
const sc_lv<8> stream_out_data_1::ap_const_lv8_B = "1011";
const sc_lv<8> stream_out_data_1::ap_const_lv8_1 = "1";
const sc_lv<9> stream_out_data_1::ap_const_lv9_1 = "1";
const sc_lv<32> stream_out_data_1::ap_const_lv32_10 = "10000";
const sc_lv<32> stream_out_data_1::ap_const_lv32_1F = "11111";
const sc_lv<11> stream_out_data_1::ap_const_lv11_A4 = "10100100";

stream_out_data_1::stream_out_data_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ultra_net_mac_mulbNq_U340 = new ultra_net_mac_mulbNq<1,1,9,2,10,11>("ultra_net_mac_mulbNq_U340");
    ultra_net_mac_mulbNq_U340->din0(grp_fu_419_p0);
    ultra_net_mac_mulbNq_U340->din1(grp_fu_419_p1);
    ultra_net_mac_mulbNq_U340->din2(grp_fu_419_p2);
    ultra_net_mac_mulbNq_U340->dout(grp_fu_419_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln65_fu_211_p2);
    sensitive << ( indvar_flatten_reg_151 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln65_reg_441_pp0_iter2_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln65_reg_441_pp0_iter2_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln65_reg_441_pp0_iter2_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);
    sensitive << ( out_V_V_full_n );
    sensitive << ( icmp_ln65_reg_441_pp0_iter2_reg );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln65_fu_205_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_cycle_fu_343_p2);
    sensitive << ( select_ln66_fu_223_p3 );

    SC_METHOD(thread_grp_fu_419_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln65_fu_205_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_419_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln65_fu_205_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_fu_419_p10 );

    SC_METHOD(thread_grp_fu_419_p10);
    sensitive << ( rowBufferIdx_V_fu_245_p2 );

    SC_METHOD(thread_grp_fu_419_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln65_fu_205_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_fu_419_p20 );

    SC_METHOD(thread_grp_fu_419_p20);
    sensitive << ( tmp_s_fu_250_p3 );

    SC_METHOD(thread_icmp_ln65_fu_205_p2);
    sensitive << ( indvar_flatten_reg_151 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln66_fu_217_p2);
    sensitive << ( cycle_0_reg_184 );
    sensitive << ( icmp_ln65_fu_205_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln879_fu_301_p2);
    sensitive << ( t_V_2_reg_162 );
    sensitive << ( icmp_ln65_fu_205_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln891_fu_283_p2);
    sensitive << ( icmp_ln65_fu_205_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ret_V_4_fu_270_p2 );

    SC_METHOD(thread_icmp_ln96_fu_295_p2);
    sensitive << ( icmp_ln65_fu_205_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( select_ln66_fu_223_p3 );

    SC_METHOD(thread_infoldIdx_V_4_fu_335_p3);
    sensitive << ( icmp_ln879_fu_301_p2 );
    sensitive << ( infoldIdx_V_fu_329_p2 );

    SC_METHOD(thread_infoldIdx_V_fu_329_p2);
    sensitive << ( t_V_2_reg_162 );

    SC_METHOD(thread_or_ln83_fu_289_p2);
    sensitive << ( tmp_9_fu_275_p3 );
    sensitive << ( icmp_ln891_fu_283_p2 );

    SC_METHOD(thread_out_V_V_blk_n);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln65_reg_441_pp0_iter2_reg );

    SC_METHOD(thread_out_V_V_din);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln65_reg_441_pp0_iter2_reg );
    sensitive << ( v1_V_reg_486 );
    sensitive << ( v2_V_reg_491 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_out_V_V_write);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln65_reg_441_pp0_iter2_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_Result_10_1_fu_380_p4);
    sensitive << ( row_buffer_1_V_q0 );

    SC_METHOD(thread_p_Result_11_1_fu_390_p3);
    sensitive << ( p_Result_10_1_fu_380_p4 );
    sensitive << ( p_Result_s_fu_358_p4 );

    SC_METHOD(thread_p_Result_9_1_fu_372_p3);
    sensitive << ( trunc_ln647_2_fu_368_p1 );
    sensitive << ( trunc_ln647_fu_354_p1 );

    SC_METHOD(thread_p_Result_s_fu_358_p4);
    sensitive << ( row_buffer_0_V_q0 );

    SC_METHOD(thread_ret_V_4_fu_270_p2);
    sensitive << ( ret_V_reg_436 );
    sensitive << ( zext_ln1353_fu_266_p1 );

    SC_METHOD(thread_ret_V_fu_199_p2);
    sensitive << ( sext_ln1354_fu_195_p1 );

    SC_METHOD(thread_rowBufferIdx_V_fu_245_p2);
    sensitive << ( startRowBufferIdx_V );
    sensitive << ( wr_V_fu_231_p4 );

    SC_METHOD(thread_row_buffer_0_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln321_fu_349_p1 );

    SC_METHOD(thread_row_buffer_0_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_row_buffer_1_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln321_fu_349_p1 );

    SC_METHOD(thread_row_buffer_1_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_select_ln66_fu_223_p3);
    sensitive << ( cycle_0_reg_184 );
    sensitive << ( icmp_ln66_fu_217_p2 );

    SC_METHOD(thread_select_ln96_fu_321_p3);
    sensitive << ( icmp_ln96_fu_295_p2 );
    sensitive << ( select_ln98_fu_313_p3 );

    SC_METHOD(thread_select_ln98_fu_313_p3);
    sensitive << ( t_V_reg_173 );
    sensitive << ( icmp_ln879_fu_301_p2 );
    sensitive << ( w_V_fu_307_p2 );

    SC_METHOD(thread_sext_ln1354_fu_195_p1);
    sensitive << ( outRowIdx_V );

    SC_METHOD(thread_sext_ln321_fu_349_p1);
    sensitive << ( add_ln321_reg_450 );

    SC_METHOD(thread_simdIdx_V_fu_241_p1);
    sensitive << ( t_V_2_reg_162 );

    SC_METHOD(thread_skip_flag_read_read_fu_112_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( skip_flag );

    SC_METHOD(thread_tmp_9_fu_275_p3);
    sensitive << ( ret_V_4_fu_270_p2 );

    SC_METHOD(thread_tmp_s_fu_250_p3);
    sensitive << ( t_V_reg_173 );
    sensitive << ( simdIdx_V_fu_241_p1 );

    SC_METHOD(thread_trunc_ln647_2_fu_368_p1);
    sensitive << ( row_buffer_1_V_q0 );

    SC_METHOD(thread_trunc_ln647_fu_354_p1);
    sensitive << ( row_buffer_0_V_q0 );

    SC_METHOD(thread_v1_V_fu_398_p3);
    sensitive << ( or_ln83_reg_455_pp0_iter1_reg );
    sensitive << ( p_Result_11_1_fu_390_p3 );

    SC_METHOD(thread_v2_V_fu_405_p3);
    sensitive << ( or_ln83_reg_455_pp0_iter1_reg );
    sensitive << ( p_Result_9_1_fu_372_p3 );

    SC_METHOD(thread_w_V_fu_307_p2);
    sensitive << ( t_V_reg_173 );

    SC_METHOD(thread_wr_V_fu_231_p4);
    sensitive << ( t_V_2_reg_162 );

    SC_METHOD(thread_zext_ln1353_fu_266_p1);
    sensitive << ( wr_V_fu_231_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( skip_flag_read_read_fu_112_p2 );
    sensitive << ( icmp_ln65_fu_205_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "stream_out_data_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_V_V_din, "(port)out_V_V_din");
    sc_trace(mVcdFile, out_V_V_full_n, "(port)out_V_V_full_n");
    sc_trace(mVcdFile, out_V_V_write, "(port)out_V_V_write");
    sc_trace(mVcdFile, row_buffer_0_V_address0, "(port)row_buffer_0_V_address0");
    sc_trace(mVcdFile, row_buffer_0_V_ce0, "(port)row_buffer_0_V_ce0");
    sc_trace(mVcdFile, row_buffer_0_V_q0, "(port)row_buffer_0_V_q0");
    sc_trace(mVcdFile, row_buffer_1_V_address0, "(port)row_buffer_1_V_address0");
    sc_trace(mVcdFile, row_buffer_1_V_ce0, "(port)row_buffer_1_V_ce0");
    sc_trace(mVcdFile, row_buffer_1_V_q0, "(port)row_buffer_1_V_q0");
    sc_trace(mVcdFile, skip_flag, "(port)skip_flag");
    sc_trace(mVcdFile, outRowIdx_V, "(port)outRowIdx_V");
    sc_trace(mVcdFile, startRowBufferIdx_V, "(port)startRowBufferIdx_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, out_V_V_blk_n, "out_V_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln65_reg_441, "icmp_ln65_reg_441");
    sc_trace(mVcdFile, icmp_ln65_reg_441_pp0_iter2_reg, "icmp_ln65_reg_441_pp0_iter2_reg");
    sc_trace(mVcdFile, indvar_flatten_reg_151, "indvar_flatten_reg_151");
    sc_trace(mVcdFile, t_V_2_reg_162, "t_V_2_reg_162");
    sc_trace(mVcdFile, t_V_reg_173, "t_V_reg_173");
    sc_trace(mVcdFile, cycle_0_reg_184, "cycle_0_reg_184");
    sc_trace(mVcdFile, skip_flag_read_read_fu_112_p2, "skip_flag_read_read_fu_112_p2");
    sc_trace(mVcdFile, ret_V_fu_199_p2, "ret_V_fu_199_p2");
    sc_trace(mVcdFile, ret_V_reg_436, "ret_V_reg_436");
    sc_trace(mVcdFile, icmp_ln65_fu_205_p2, "icmp_ln65_fu_205_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln65_reg_441_pp0_iter1_reg, "icmp_ln65_reg_441_pp0_iter1_reg");
    sc_trace(mVcdFile, add_ln65_fu_211_p2, "add_ln65_fu_211_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, grp_fu_419_p3, "grp_fu_419_p3");
    sc_trace(mVcdFile, add_ln321_reg_450, "add_ln321_reg_450");
    sc_trace(mVcdFile, or_ln83_fu_289_p2, "or_ln83_fu_289_p2");
    sc_trace(mVcdFile, or_ln83_reg_455, "or_ln83_reg_455");
    sc_trace(mVcdFile, or_ln83_reg_455_pp0_iter1_reg, "or_ln83_reg_455_pp0_iter1_reg");
    sc_trace(mVcdFile, select_ln96_fu_321_p3, "select_ln96_fu_321_p3");
    sc_trace(mVcdFile, infoldIdx_V_4_fu_335_p3, "infoldIdx_V_4_fu_335_p3");
    sc_trace(mVcdFile, cycle_fu_343_p2, "cycle_fu_343_p2");
    sc_trace(mVcdFile, v1_V_fu_398_p3, "v1_V_fu_398_p3");
    sc_trace(mVcdFile, v1_V_reg_486, "v1_V_reg_486");
    sc_trace(mVcdFile, v2_V_fu_405_p3, "v2_V_fu_405_p3");
    sc_trace(mVcdFile, v2_V_reg_491, "v2_V_reg_491");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, sext_ln321_fu_349_p1, "sext_ln321_fu_349_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, sext_ln1354_fu_195_p1, "sext_ln1354_fu_195_p1");
    sc_trace(mVcdFile, icmp_ln66_fu_217_p2, "icmp_ln66_fu_217_p2");
    sc_trace(mVcdFile, wr_V_fu_231_p4, "wr_V_fu_231_p4");
    sc_trace(mVcdFile, simdIdx_V_fu_241_p1, "simdIdx_V_fu_241_p1");
    sc_trace(mVcdFile, tmp_s_fu_250_p3, "tmp_s_fu_250_p3");
    sc_trace(mVcdFile, rowBufferIdx_V_fu_245_p2, "rowBufferIdx_V_fu_245_p2");
    sc_trace(mVcdFile, zext_ln1353_fu_266_p1, "zext_ln1353_fu_266_p1");
    sc_trace(mVcdFile, ret_V_4_fu_270_p2, "ret_V_4_fu_270_p2");
    sc_trace(mVcdFile, tmp_9_fu_275_p3, "tmp_9_fu_275_p3");
    sc_trace(mVcdFile, icmp_ln891_fu_283_p2, "icmp_ln891_fu_283_p2");
    sc_trace(mVcdFile, select_ln66_fu_223_p3, "select_ln66_fu_223_p3");
    sc_trace(mVcdFile, icmp_ln879_fu_301_p2, "icmp_ln879_fu_301_p2");
    sc_trace(mVcdFile, w_V_fu_307_p2, "w_V_fu_307_p2");
    sc_trace(mVcdFile, icmp_ln96_fu_295_p2, "icmp_ln96_fu_295_p2");
    sc_trace(mVcdFile, select_ln98_fu_313_p3, "select_ln98_fu_313_p3");
    sc_trace(mVcdFile, infoldIdx_V_fu_329_p2, "infoldIdx_V_fu_329_p2");
    sc_trace(mVcdFile, trunc_ln647_2_fu_368_p1, "trunc_ln647_2_fu_368_p1");
    sc_trace(mVcdFile, trunc_ln647_fu_354_p1, "trunc_ln647_fu_354_p1");
    sc_trace(mVcdFile, p_Result_10_1_fu_380_p4, "p_Result_10_1_fu_380_p4");
    sc_trace(mVcdFile, p_Result_s_fu_358_p4, "p_Result_s_fu_358_p4");
    sc_trace(mVcdFile, p_Result_11_1_fu_390_p3, "p_Result_11_1_fu_390_p3");
    sc_trace(mVcdFile, p_Result_9_1_fu_372_p3, "p_Result_9_1_fu_372_p3");
    sc_trace(mVcdFile, grp_fu_419_p0, "grp_fu_419_p0");
    sc_trace(mVcdFile, grp_fu_419_p1, "grp_fu_419_p1");
    sc_trace(mVcdFile, grp_fu_419_p2, "grp_fu_419_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_419_p10, "grp_fu_419_p10");
    sc_trace(mVcdFile, grp_fu_419_p20, "grp_fu_419_p20");
#endif

    }
}

stream_out_data_1::~stream_out_data_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete ultra_net_mac_mulbNq_U340;
}

void stream_out_data_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, skip_flag_read_read_fu_112_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, skip_flag_read_read_fu_112_p2.read()))) {
            ap_enable_reg_pp0_iter3 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_205_p2.read()))) {
        cycle_0_reg_184 = cycle_fu_343_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, skip_flag_read_read_fu_112_p2.read()))) {
        cycle_0_reg_184 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_205_p2.read()))) {
        indvar_flatten_reg_151 = add_ln65_fu_211_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, skip_flag_read_read_fu_112_p2.read()))) {
        indvar_flatten_reg_151 = ap_const_lv12_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_205_p2.read()))) {
        t_V_2_reg_162 = infoldIdx_V_4_fu_335_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, skip_flag_read_read_fu_112_p2.read()))) {
        t_V_2_reg_162 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_205_p2.read()))) {
        t_V_reg_173 = select_ln96_fu_321_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, skip_flag_read_read_fu_112_p2.read()))) {
        t_V_reg_173 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_205_p2.read()))) {
        add_ln321_reg_450 = grp_fu_419_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln65_reg_441 = icmp_ln65_fu_205_p2.read();
        icmp_ln65_reg_441_pp0_iter1_reg = icmp_ln65_reg_441.read();
        or_ln83_reg_455_pp0_iter1_reg = or_ln83_reg_455.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln65_reg_441_pp0_iter2_reg = icmp_ln65_reg_441_pp0_iter1_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_205_p2.read()))) {
        or_ln83_reg_455 = or_ln83_fu_289_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, skip_flag_read_read_fu_112_p2.read()))) {
        ret_V_reg_436 = ret_V_fu_199_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_reg_441_pp0_iter1_reg.read()))) {
        v1_V_reg_486 = v1_V_fu_398_p3.read();
        v2_V_reg_491 = v2_V_fu_405_p3.read();
    }
}

void stream_out_data_1::thread_add_ln65_fu_211_p2() {
    add_ln65_fu_211_p2 = (!indvar_flatten_reg_151.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(indvar_flatten_reg_151.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void stream_out_data_1::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void stream_out_data_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void stream_out_data_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[2];
}

void stream_out_data_1::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void stream_out_data_1::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(icmp_ln65_reg_441_pp0_iter2_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()));
}

void stream_out_data_1::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(icmp_ln65_reg_441_pp0_iter2_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()));
}

void stream_out_data_1::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(icmp_ln65_reg_441_pp0_iter2_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()));
}

void stream_out_data_1::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void stream_out_data_1::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void stream_out_data_1::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void stream_out_data_1::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = (esl_seteq<1,1,1>(icmp_ln65_reg_441_pp0_iter2_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()));
}

void stream_out_data_1::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln65_fu_205_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void stream_out_data_1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void stream_out_data_1::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void stream_out_data_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void stream_out_data_1::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void stream_out_data_1::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void stream_out_data_1::thread_cycle_fu_343_p2() {
    cycle_fu_343_p2 = (!ap_const_lv9_1.is_01() || !select_ln66_fu_223_p3.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_1) + sc_biguint<9>(select_ln66_fu_223_p3.read()));
}

void stream_out_data_1::thread_grp_fu_419_p0() {
    grp_fu_419_p0 =  (sc_lv<9>) (ap_const_lv11_A4);
}

void stream_out_data_1::thread_grp_fu_419_p1() {
    grp_fu_419_p1 =  (sc_lv<2>) (grp_fu_419_p10.read());
}

void stream_out_data_1::thread_grp_fu_419_p10() {
    grp_fu_419_p10 = esl_zext<11,2>(rowBufferIdx_V_fu_245_p2.read());
}

void stream_out_data_1::thread_grp_fu_419_p2() {
    grp_fu_419_p2 =  (sc_lv<10>) (grp_fu_419_p20.read());
}

void stream_out_data_1::thread_grp_fu_419_p20() {
    grp_fu_419_p20 = esl_zext<11,10>(tmp_s_fu_250_p3.read());
}

void stream_out_data_1::thread_icmp_ln65_fu_205_p2() {
    icmp_ln65_fu_205_p2 = (!indvar_flatten_reg_151.read().is_01() || !ap_const_lv12_F60.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_151.read() == ap_const_lv12_F60);
}

void stream_out_data_1::thread_icmp_ln66_fu_217_p2() {
    icmp_ln66_fu_217_p2 = (!cycle_0_reg_184.read().is_01() || !ap_const_lv9_1EC.is_01())? sc_lv<1>(): sc_lv<1>(cycle_0_reg_184.read() == ap_const_lv9_1EC);
}

void stream_out_data_1::thread_icmp_ln879_fu_301_p2() {
    icmp_ln879_fu_301_p2 = (!t_V_2_reg_162.read().is_01() || !ap_const_lv8_B.is_01())? sc_lv<1>(): sc_lv<1>(t_V_2_reg_162.read() == ap_const_lv8_B);
}

void stream_out_data_1::thread_icmp_ln891_fu_283_p2() {
    icmp_ln891_fu_283_p2 = (!ret_V_4_fu_270_p2.read().is_01() || !ap_const_lv11_27.is_01())? sc_lv<1>(): (sc_bigint<11>(ret_V_4_fu_270_p2.read()) > sc_bigint<11>(ap_const_lv11_27));
}

void stream_out_data_1::thread_icmp_ln96_fu_295_p2() {
    icmp_ln96_fu_295_p2 = (!select_ln66_fu_223_p3.read().is_01() || !ap_const_lv9_1EB.is_01())? sc_lv<1>(): sc_lv<1>(select_ln66_fu_223_p3.read() == ap_const_lv9_1EB);
}

void stream_out_data_1::thread_infoldIdx_V_4_fu_335_p3() {
    infoldIdx_V_4_fu_335_p3 = (!icmp_ln879_fu_301_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln879_fu_301_p2.read()[0].to_bool())? ap_const_lv8_0: infoldIdx_V_fu_329_p2.read());
}

void stream_out_data_1::thread_infoldIdx_V_fu_329_p2() {
    infoldIdx_V_fu_329_p2 = (!ap_const_lv8_1.is_01() || !t_V_2_reg_162.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_1) + sc_biguint<8>(t_V_2_reg_162.read()));
}

void stream_out_data_1::thread_or_ln83_fu_289_p2() {
    or_ln83_fu_289_p2 = (tmp_9_fu_275_p3.read() | icmp_ln891_fu_283_p2.read());
}

void stream_out_data_1::thread_out_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln65_reg_441_pp0_iter2_reg.read(), ap_const_lv1_0))) {
        out_V_V_blk_n = out_V_V_full_n.read();
    } else {
        out_V_V_blk_n = ap_const_logic_1;
    }
}

void stream_out_data_1::thread_out_V_V_din() {
    out_V_V_din = esl_concat<32,32>(v1_V_reg_486.read(), v2_V_reg_491.read());
}

void stream_out_data_1::thread_out_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_reg_441_pp0_iter2_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        out_V_V_write = ap_const_logic_1;
    } else {
        out_V_V_write = ap_const_logic_0;
    }
}

void stream_out_data_1::thread_p_Result_10_1_fu_380_p4() {
    p_Result_10_1_fu_380_p4 = row_buffer_1_V_q0.read().range(31, 16);
}

void stream_out_data_1::thread_p_Result_11_1_fu_390_p3() {
    p_Result_11_1_fu_390_p3 = esl_concat<16,16>(p_Result_10_1_fu_380_p4.read(), p_Result_s_fu_358_p4.read());
}

void stream_out_data_1::thread_p_Result_9_1_fu_372_p3() {
    p_Result_9_1_fu_372_p3 = esl_concat<16,16>(trunc_ln647_2_fu_368_p1.read(), trunc_ln647_fu_354_p1.read());
}

void stream_out_data_1::thread_p_Result_s_fu_358_p4() {
    p_Result_s_fu_358_p4 = row_buffer_0_V_q0.read().range(31, 16);
}

void stream_out_data_1::thread_ret_V_4_fu_270_p2() {
    ret_V_4_fu_270_p2 = (!zext_ln1353_fu_266_p1.read().is_01() || !ret_V_reg_436.read().is_01())? sc_lv<11>(): (sc_biguint<11>(zext_ln1353_fu_266_p1.read()) + sc_biguint<11>(ret_V_reg_436.read()));
}

void stream_out_data_1::thread_ret_V_fu_199_p2() {
    ret_V_fu_199_p2 = (!sext_ln1354_fu_195_p1.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<11>(): (sc_bigint<11>(sext_ln1354_fu_195_p1.read()) + sc_bigint<11>(ap_const_lv11_7FF));
}

void stream_out_data_1::thread_rowBufferIdx_V_fu_245_p2() {
    rowBufferIdx_V_fu_245_p2 = (!wr_V_fu_231_p4.read().is_01() || !startRowBufferIdx_V.read().is_01())? sc_lv<2>(): (sc_biguint<2>(wr_V_fu_231_p4.read()) + sc_biguint<2>(startRowBufferIdx_V.read()));
}

void stream_out_data_1::thread_row_buffer_0_V_address0() {
    row_buffer_0_V_address0 =  (sc_lv<10>) (sext_ln321_fu_349_p1.read());
}

void stream_out_data_1::thread_row_buffer_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        row_buffer_0_V_ce0 = ap_const_logic_1;
    } else {
        row_buffer_0_V_ce0 = ap_const_logic_0;
    }
}

void stream_out_data_1::thread_row_buffer_1_V_address0() {
    row_buffer_1_V_address0 =  (sc_lv<10>) (sext_ln321_fu_349_p1.read());
}

void stream_out_data_1::thread_row_buffer_1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        row_buffer_1_V_ce0 = ap_const_logic_1;
    } else {
        row_buffer_1_V_ce0 = ap_const_logic_0;
    }
}

void stream_out_data_1::thread_select_ln66_fu_223_p3() {
    select_ln66_fu_223_p3 = (!icmp_ln66_fu_217_p2.read()[0].is_01())? sc_lv<9>(): ((icmp_ln66_fu_217_p2.read()[0].to_bool())? ap_const_lv9_0: cycle_0_reg_184.read());
}

void stream_out_data_1::thread_select_ln96_fu_321_p3() {
    select_ln96_fu_321_p3 = (!icmp_ln96_fu_295_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln96_fu_295_p2.read()[0].to_bool())? ap_const_lv8_0: select_ln98_fu_313_p3.read());
}

void stream_out_data_1::thread_select_ln98_fu_313_p3() {
    select_ln98_fu_313_p3 = (!icmp_ln879_fu_301_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln879_fu_301_p2.read()[0].to_bool())? w_V_fu_307_p2.read(): t_V_reg_173.read());
}

void stream_out_data_1::thread_sext_ln1354_fu_195_p1() {
    sext_ln1354_fu_195_p1 = esl_sext<11,10>(outRowIdx_V.read());
}

void stream_out_data_1::thread_sext_ln321_fu_349_p1() {
    sext_ln321_fu_349_p1 = esl_sext<64,11>(add_ln321_reg_450.read());
}

void stream_out_data_1::thread_simdIdx_V_fu_241_p1() {
    simdIdx_V_fu_241_p1 = t_V_2_reg_162.read().range(2-1, 0);
}

void stream_out_data_1::thread_skip_flag_read_read_fu_112_p2() {
    skip_flag_read_read_fu_112_p2 =  (sc_lv<1>) (skip_flag.read());
}

void stream_out_data_1::thread_tmp_9_fu_275_p3() {
    tmp_9_fu_275_p3 = ret_V_4_fu_270_p2.read().range(10, 10);
}

void stream_out_data_1::thread_tmp_s_fu_250_p3() {
    tmp_s_fu_250_p3 = esl_concat<8,2>(t_V_reg_173.read(), simdIdx_V_fu_241_p1.read());
}

void stream_out_data_1::thread_trunc_ln647_2_fu_368_p1() {
    trunc_ln647_2_fu_368_p1 = row_buffer_1_V_q0.read().range(16-1, 0);
}

void stream_out_data_1::thread_trunc_ln647_fu_354_p1() {
    trunc_ln647_fu_354_p1 = row_buffer_0_V_q0.read().range(16-1, 0);
}

void stream_out_data_1::thread_v1_V_fu_398_p3() {
    v1_V_fu_398_p3 = (!or_ln83_reg_455_pp0_iter1_reg.read()[0].is_01())? sc_lv<32>(): ((or_ln83_reg_455_pp0_iter1_reg.read()[0].to_bool())? ap_const_lv32_0: p_Result_11_1_fu_390_p3.read());
}

void stream_out_data_1::thread_v2_V_fu_405_p3() {
    v2_V_fu_405_p3 = (!or_ln83_reg_455_pp0_iter1_reg.read()[0].is_01())? sc_lv<32>(): ((or_ln83_reg_455_pp0_iter1_reg.read()[0].to_bool())? ap_const_lv32_0: p_Result_9_1_fu_372_p3.read());
}

void stream_out_data_1::thread_w_V_fu_307_p2() {
    w_V_fu_307_p2 = (!ap_const_lv8_1.is_01() || !t_V_reg_173.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_1) + sc_biguint<8>(t_V_reg_173.read()));
}

void stream_out_data_1::thread_wr_V_fu_231_p4() {
    wr_V_fu_231_p4 = t_V_2_reg_162.read().range(3, 2);
}

void stream_out_data_1::thread_zext_ln1353_fu_266_p1() {
    zext_ln1353_fu_266_p1 = esl_zext<11,2>(wr_V_fu_231_p4.read());
}

void stream_out_data_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, skip_flag_read_read_fu_112_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(skip_flag_read_read_fu_112_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln65_fu_205_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln65_fu_205_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

